// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/token/v1/token.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.identity.token.v1;

@com.google.protobuf.Generated
public interface TokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.token.v1.Token)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The jti.
   */
  java.lang.String getJti();
  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The bytes for jti.
   */
  com.google.protobuf.ByteString
      getJtiBytes();

  /**
   * <code>bytes value = 2 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the issuedAt field is set.
   */
  boolean hasIssuedAt();
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
   * @return The issuedAt.
   */
  com.google.protobuf.Timestamp getIssuedAt();
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getIssuedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the expiredAt field is set.
   */
  boolean hasExpiredAt();
  /**
   * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
   * @return The expiredAt.
   */
  com.google.protobuf.Timestamp getExpiredAt();
  /**
   * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiredAtOrBuilder();
}
