// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/token/v1/token.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.identity.token.v1;

/**
 * Protobuf type {@code identity.token.v1.Token}
 */
@com.google.protobuf.Generated
public final class Token extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:identity.token.v1.Token)
    TokenOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Token");
  }
  // Use Token.newBuilder() to construct.
  private Token(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Token() {
    jti_ = "";
    value_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.identity.token.v1.TokenOuterClass.internal_static_identity_token_v1_Token_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.identity.token.v1.TokenOuterClass.internal_static_identity_token_v1_Token_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.identity.token.v1.Token.class, com.josestg.pb.identity.token.v1.Token.Builder.class);
  }

  private int bitField0_;
  public static final int JTI_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jti_ = "";
  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The jti.
   */
  @java.lang.Override
  public java.lang.String getJti() {
    java.lang.Object ref = jti_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jti_ = s;
      return s;
    }
  }
  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The bytes for jti.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJtiBytes() {
    java.lang.Object ref = jti_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jti_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes value = 2 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValue() {
    return value_;
  }

  public static final int ISSUED_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp issuedAt_;
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the issuedAt field is set.
   */
  @java.lang.Override
  public boolean hasIssuedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
   * @return The issuedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getIssuedAt() {
    return issuedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : issuedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getIssuedAtOrBuilder() {
    return issuedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : issuedAt_;
  }

  public static final int EXPIRED_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp expiredAt_;
  /**
   * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the expiredAt field is set.
   */
  @java.lang.Override
  public boolean hasExpiredAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
   * @return The expiredAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpiredAt() {
    return expiredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpiredAtOrBuilder() {
    return expiredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jti_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, jti_);
    }
    if (!value_.isEmpty()) {
      output.writeBytes(2, value_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getIssuedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getExpiredAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jti_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, jti_);
    }
    if (!value_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, value_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getIssuedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExpiredAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.identity.token.v1.Token)) {
      return super.equals(obj);
    }
    com.josestg.pb.identity.token.v1.Token other = (com.josestg.pb.identity.token.v1.Token) obj;

    if (!getJti()
        .equals(other.getJti())) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (hasIssuedAt() != other.hasIssuedAt()) return false;
    if (hasIssuedAt()) {
      if (!getIssuedAt()
          .equals(other.getIssuedAt())) return false;
    }
    if (hasExpiredAt() != other.hasExpiredAt()) return false;
    if (hasExpiredAt()) {
      if (!getExpiredAt()
          .equals(other.getExpiredAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JTI_FIELD_NUMBER;
    hash = (53 * hash) + getJti().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    if (hasIssuedAt()) {
      hash = (37 * hash) + ISSUED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getIssuedAt().hashCode();
    }
    if (hasExpiredAt()) {
      hash = (37 * hash) + EXPIRED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiredAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.identity.token.v1.Token parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.identity.token.v1.Token parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.identity.token.v1.Token parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.identity.token.v1.Token prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code identity.token.v1.Token}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:identity.token.v1.Token)
      com.josestg.pb.identity.token.v1.TokenOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.identity.token.v1.TokenOuterClass.internal_static_identity_token_v1_Token_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.identity.token.v1.TokenOuterClass.internal_static_identity_token_v1_Token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.identity.token.v1.Token.class, com.josestg.pb.identity.token.v1.Token.Builder.class);
    }

    // Construct using com.josestg.pb.identity.token.v1.Token.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetIssuedAtFieldBuilder();
        internalGetExpiredAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jti_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      issuedAt_ = null;
      if (issuedAtBuilder_ != null) {
        issuedAtBuilder_.dispose();
        issuedAtBuilder_ = null;
      }
      expiredAt_ = null;
      if (expiredAtBuilder_ != null) {
        expiredAtBuilder_.dispose();
        expiredAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.identity.token.v1.TokenOuterClass.internal_static_identity_token_v1_Token_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.identity.token.v1.Token getDefaultInstanceForType() {
      return com.josestg.pb.identity.token.v1.Token.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.identity.token.v1.Token build() {
      com.josestg.pb.identity.token.v1.Token result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.identity.token.v1.Token buildPartial() {
      com.josestg.pb.identity.token.v1.Token result = new com.josestg.pb.identity.token.v1.Token(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.josestg.pb.identity.token.v1.Token result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jti_ = jti_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = value_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.issuedAt_ = issuedAtBuilder_ == null
            ? issuedAt_
            : issuedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.expiredAt_ = expiredAtBuilder_ == null
            ? expiredAt_
            : expiredAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.identity.token.v1.Token) {
        return mergeFrom((com.josestg.pb.identity.token.v1.Token)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.identity.token.v1.Token other) {
      if (other == com.josestg.pb.identity.token.v1.Token.getDefaultInstance()) return this;
      if (!other.getJti().isEmpty()) {
        jti_ = other.jti_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        setValue(other.getValue());
      }
      if (other.hasIssuedAt()) {
        mergeIssuedAt(other.getIssuedAt());
      }
      if (other.hasExpiredAt()) {
        mergeExpiredAt(other.getExpiredAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jti_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              value_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetIssuedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetExpiredAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object jti_ = "";
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @return The jti.
     */
    public java.lang.String getJti() {
      java.lang.Object ref = jti_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jti_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @return The bytes for jti.
     */
    public com.google.protobuf.ByteString
        getJtiBytes() {
      java.lang.Object ref = jti_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jti_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @param value The jti to set.
     * @return This builder for chaining.
     */
    public Builder setJti(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jti_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearJti() {
      jti_ = getDefaultInstance().getJti();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for jti to set.
     * @return This builder for chaining.
     */
    public Builder setJtiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jti_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes value = 2 [json_name = "value", (.buf.validate.field) = { ... }</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    /**
     * <code>bytes value = 2 [json_name = "value", (.buf.validate.field) = { ... }</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes value = 2 [json_name = "value", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp issuedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> issuedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     * @return Whether the issuedAt field is set.
     */
    public boolean hasIssuedAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     * @return The issuedAt.
     */
    public com.google.protobuf.Timestamp getIssuedAt() {
      if (issuedAtBuilder_ == null) {
        return issuedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : issuedAt_;
      } else {
        return issuedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setIssuedAt(com.google.protobuf.Timestamp value) {
      if (issuedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        issuedAt_ = value;
      } else {
        issuedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setIssuedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (issuedAtBuilder_ == null) {
        issuedAt_ = builderForValue.build();
      } else {
        issuedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeIssuedAt(com.google.protobuf.Timestamp value) {
      if (issuedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          issuedAt_ != null &&
          issuedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getIssuedAtBuilder().mergeFrom(value);
        } else {
          issuedAt_ = value;
        }
      } else {
        issuedAtBuilder_.mergeFrom(value);
      }
      if (issuedAt_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearIssuedAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      issuedAt_ = null;
      if (issuedAtBuilder_ != null) {
        issuedAtBuilder_.dispose();
        issuedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getIssuedAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetIssuedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getIssuedAtOrBuilder() {
      if (issuedAtBuilder_ != null) {
        return issuedAtBuilder_.getMessageOrBuilder();
      } else {
        return issuedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : issuedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp issued_at = 3 [json_name = "issued_at", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetIssuedAtFieldBuilder() {
      if (issuedAtBuilder_ == null) {
        issuedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getIssuedAt(),
                getParentForChildren(),
                isClean());
        issuedAt_ = null;
      }
      return issuedAtBuilder_;
    }

    private com.google.protobuf.Timestamp expiredAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiredAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     * @return Whether the expiredAt field is set.
     */
    public boolean hasExpiredAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     * @return The expiredAt.
     */
    public com.google.protobuf.Timestamp getExpiredAt() {
      if (expiredAtBuilder_ == null) {
        return expiredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
      } else {
        return expiredAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setExpiredAt(com.google.protobuf.Timestamp value) {
      if (expiredAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiredAt_ = value;
      } else {
        expiredAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setExpiredAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiredAtBuilder_ == null) {
        expiredAt_ = builderForValue.build();
      } else {
        expiredAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeExpiredAt(com.google.protobuf.Timestamp value) {
      if (expiredAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          expiredAt_ != null &&
          expiredAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getExpiredAtBuilder().mergeFrom(value);
        } else {
          expiredAt_ = value;
        }
      } else {
        expiredAtBuilder_.mergeFrom(value);
      }
      if (expiredAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearExpiredAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      expiredAt_ = null;
      if (expiredAtBuilder_ != null) {
        expiredAtBuilder_.dispose();
        expiredAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiredAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetExpiredAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiredAtOrBuilder() {
      if (expiredAtBuilder_ != null) {
        return expiredAtBuilder_.getMessageOrBuilder();
      } else {
        return expiredAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expired_at = 4 [json_name = "expired_at", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetExpiredAtFieldBuilder() {
      if (expiredAtBuilder_ == null) {
        expiredAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpiredAt(),
                getParentForChildren(),
                isClean());
        expiredAt_ = null;
      }
      return expiredAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:identity.token.v1.Token)
  }

  // @@protoc_insertion_point(class_scope:identity.token.v1.Token)
  private static final com.josestg.pb.identity.token.v1.Token DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.identity.token.v1.Token();
  }

  public static com.josestg.pb.identity.token.v1.Token getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Token>
      PARSER = new com.google.protobuf.AbstractParser<Token>() {
    @java.lang.Override
    public Token parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Token> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Token> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.identity.token.v1.Token getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

