// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/token/v1/token.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.identity.token.v1;

@com.google.protobuf.Generated
public final class TokenOuterClass extends com.google.protobuf.GeneratedFile {
  private TokenOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "TokenOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_token_v1_Token_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_identity_token_v1_Token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035identity/token/v1/token.proto\022\021identit" +
      "y.token.v1\032\037google/protobuf/timestamp.pr" +
      "oto\032\033buf/validate/validate.proto\"\312\001\n\005Tok" +
      "en\022\035\n\003jti\030\001 \001(\tB\013\272H\010r\003\210\002\001\310\001\001R\003jti\022\034\n\005val" +
      "ue\030\002 \001(\014B\006\272H\003\310\001\001R\005value\022@\n\tissued_at\030\003 \001" +
      "(\0132\032.google.protobuf.TimestampB\006\272H\003\310\001\001R\t" +
      "issued_at\022B\n\nexpired_at\030\004 \001(\0132\032.google.p" +
      "rotobuf.TimestampB\006\272H\003\310\001\001R\nexpired_atBX\n" +
      " com.josestg.pb.identity.token.v1P\001Z2git" +
      "hub.com/josestg/pb/go/identity/token/v1;" +
      "tokenpbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_identity_token_v1_Token_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_identity_token_v1_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_identity_token_v1_Token_descriptor,
        new java.lang.String[] { "Jti", "Value", "IssuedAt", "ExpiredAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
