// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/audit/v1/audit.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.shared.audit.v1;

@com.google.protobuf.Generated
public interface AuditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shared.audit.v1.Audit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "created_at"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "created_at"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "created_at"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 3 [json_name = "updated_at"];</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3 [json_name = "updated_at"];</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 3 [json_name = "updated_at"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deleted_at"];</code>
   * @return Whether the deletedAt field is set.
   */
  boolean hasDeletedAt();
  /**
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deleted_at"];</code>
   * @return The deletedAt.
   */
  com.google.protobuf.Timestamp getDeletedAt();
  /**
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deleted_at"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder();
}
