// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/audit/v1/audit.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.shared.audit.v1;

@com.google.protobuf.Generated
public final class AuditOuterClass extends com.google.protobuf.GeneratedFile {
  private AuditOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AuditOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shared_audit_v1_Audit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_shared_audit_v1_Audit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033shared/audit/v1/audit.proto\022\017shared.au" +
      "dit.v1\032\037google/protobuf/timestamp.proto\"" +
      "\317\001\n\005Audit\022:\n\ncreated_at\030\002 \001(\0132\032.google.p" +
      "rotobuf.TimestampR\ncreated_at\022:\n\nupdated" +
      "_at\030\003 \001(\0132\032.google.protobuf.TimestampR\nu" +
      "pdated_at\022?\n\ndeleted_at\030\004 \001(\0132\032.google.p" +
      "rotobuf.TimestampH\000R\ndeleted_at\210\001\001B\r\n\013_d" +
      "eleted_atBT\n\036com.josestg.pb.shared.audit" +
      ".v1P\001Z0github.com/josestg/pb/go/shared/a" +
      "udit/v1;auditpbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_shared_audit_v1_Audit_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_shared_audit_v1_Audit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_shared_audit_v1_Audit_descriptor,
        new java.lang.String[] { "CreatedAt", "UpdatedAt", "DeletedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
