// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: team/project/feature/v1/example.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.team.project.feature.v1;

/**
 * Protobuf type {@code team.project.feature.v1.ExampleRequest}
 */
@com.google.protobuf.Generated
public final class ExampleRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:team.project.feature.v1.ExampleRequest)
    ExampleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ExampleRequest");
  }
  // Use ExampleRequest.newBuilder() to construct.
  private ExampleRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExampleRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.team.project.feature.v1.ExampleRequest.class, com.josestg.pb.team.project.feature.v1.ExampleRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CREATE_FIELD_NUMBER = 1;
  private com.josestg.pb.session.v1.CreateRequest create_;
  /**
   * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
   * @return Whether the create field is set.
   */
  @java.lang.Override
  public boolean hasCreate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
   * @return The create.
   */
  @java.lang.Override
  public com.josestg.pb.session.v1.CreateRequest getCreate() {
    return create_ == null ? com.josestg.pb.session.v1.CreateRequest.getDefaultInstance() : create_;
  }
  /**
   * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
   */
  @java.lang.Override
  public com.josestg.pb.session.v1.CreateRequestOrBuilder getCreateOrBuilder() {
    return create_ == null ? com.josestg.pb.session.v1.CreateRequest.getDefaultInstance() : create_;
  }

  public static final int AUDIT_FIELD_NUMBER = 2;
  private com.josestg.pb.shared.audit.v1.Audit audit_;
  /**
   * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
   * @return Whether the audit field is set.
   */
  @java.lang.Override
  public boolean hasAudit() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
   * @return The audit.
   */
  @java.lang.Override
  public com.josestg.pb.shared.audit.v1.Audit getAudit() {
    return audit_ == null ? com.josestg.pb.shared.audit.v1.Audit.getDefaultInstance() : audit_;
  }
  /**
   * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
   */
  @java.lang.Override
  public com.josestg.pb.shared.audit.v1.AuditOrBuilder getAuditOrBuilder() {
    return audit_ == null ? com.josestg.pb.shared.audit.v1.Audit.getDefaultInstance() : audit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCreate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getAudit());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCreate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAudit());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.team.project.feature.v1.ExampleRequest)) {
      return super.equals(obj);
    }
    com.josestg.pb.team.project.feature.v1.ExampleRequest other = (com.josestg.pb.team.project.feature.v1.ExampleRequest) obj;

    if (hasCreate() != other.hasCreate()) return false;
    if (hasCreate()) {
      if (!getCreate()
          .equals(other.getCreate())) return false;
    }
    if (hasAudit() != other.hasAudit()) return false;
    if (hasAudit()) {
      if (!getAudit()
          .equals(other.getAudit())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCreate()) {
      hash = (37 * hash) + CREATE_FIELD_NUMBER;
      hash = (53 * hash) + getCreate().hashCode();
    }
    if (hasAudit()) {
      hash = (37 * hash) + AUDIT_FIELD_NUMBER;
      hash = (53 * hash) + getAudit().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.team.project.feature.v1.ExampleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code team.project.feature.v1.ExampleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:team.project.feature.v1.ExampleRequest)
      com.josestg.pb.team.project.feature.v1.ExampleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.team.project.feature.v1.ExampleRequest.class, com.josestg.pb.team.project.feature.v1.ExampleRequest.Builder.class);
    }

    // Construct using com.josestg.pb.team.project.feature.v1.ExampleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCreateFieldBuilder();
        internalGetAuditFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      create_ = null;
      if (createBuilder_ != null) {
        createBuilder_.dispose();
        createBuilder_ = null;
      }
      audit_ = null;
      if (auditBuilder_ != null) {
        auditBuilder_.dispose();
        auditBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleRequest_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.team.project.feature.v1.ExampleRequest getDefaultInstanceForType() {
      return com.josestg.pb.team.project.feature.v1.ExampleRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.team.project.feature.v1.ExampleRequest build() {
      com.josestg.pb.team.project.feature.v1.ExampleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.team.project.feature.v1.ExampleRequest buildPartial() {
      com.josestg.pb.team.project.feature.v1.ExampleRequest result = new com.josestg.pb.team.project.feature.v1.ExampleRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.josestg.pb.team.project.feature.v1.ExampleRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.create_ = createBuilder_ == null
            ? create_
            : createBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.audit_ = auditBuilder_ == null
            ? audit_
            : auditBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.team.project.feature.v1.ExampleRequest) {
        return mergeFrom((com.josestg.pb.team.project.feature.v1.ExampleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.team.project.feature.v1.ExampleRequest other) {
      if (other == com.josestg.pb.team.project.feature.v1.ExampleRequest.getDefaultInstance()) return this;
      if (other.hasCreate()) {
        mergeCreate(other.getCreate());
      }
      if (other.hasAudit()) {
        mergeAudit(other.getAudit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetCreateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetAuditFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.josestg.pb.session.v1.CreateRequest create_;
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.session.v1.CreateRequest, com.josestg.pb.session.v1.CreateRequest.Builder, com.josestg.pb.session.v1.CreateRequestOrBuilder> createBuilder_;
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     * @return Whether the create field is set.
     */
    public boolean hasCreate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     * @return The create.
     */
    public com.josestg.pb.session.v1.CreateRequest getCreate() {
      if (createBuilder_ == null) {
        return create_ == null ? com.josestg.pb.session.v1.CreateRequest.getDefaultInstance() : create_;
      } else {
        return createBuilder_.getMessage();
      }
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     */
    public Builder setCreate(com.josestg.pb.session.v1.CreateRequest value) {
      if (createBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        create_ = value;
      } else {
        createBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     */
    public Builder setCreate(
        com.josestg.pb.session.v1.CreateRequest.Builder builderForValue) {
      if (createBuilder_ == null) {
        create_ = builderForValue.build();
      } else {
        createBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     */
    public Builder mergeCreate(com.josestg.pb.session.v1.CreateRequest value) {
      if (createBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          create_ != null &&
          create_ != com.josestg.pb.session.v1.CreateRequest.getDefaultInstance()) {
          getCreateBuilder().mergeFrom(value);
        } else {
          create_ = value;
        }
      } else {
        createBuilder_.mergeFrom(value);
      }
      if (create_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     */
    public Builder clearCreate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      create_ = null;
      if (createBuilder_ != null) {
        createBuilder_.dispose();
        createBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     */
    public com.josestg.pb.session.v1.CreateRequest.Builder getCreateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetCreateFieldBuilder().getBuilder();
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     */
    public com.josestg.pb.session.v1.CreateRequestOrBuilder getCreateOrBuilder() {
      if (createBuilder_ != null) {
        return createBuilder_.getMessageOrBuilder();
      } else {
        return create_ == null ?
            com.josestg.pb.session.v1.CreateRequest.getDefaultInstance() : create_;
      }
    }
    /**
     * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.session.v1.CreateRequest, com.josestg.pb.session.v1.CreateRequest.Builder, com.josestg.pb.session.v1.CreateRequestOrBuilder> 
        internalGetCreateFieldBuilder() {
      if (createBuilder_ == null) {
        createBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.josestg.pb.session.v1.CreateRequest, com.josestg.pb.session.v1.CreateRequest.Builder, com.josestg.pb.session.v1.CreateRequestOrBuilder>(
                getCreate(),
                getParentForChildren(),
                isClean());
        create_ = null;
      }
      return createBuilder_;
    }

    private com.josestg.pb.shared.audit.v1.Audit audit_;
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.shared.audit.v1.Audit, com.josestg.pb.shared.audit.v1.Audit.Builder, com.josestg.pb.shared.audit.v1.AuditOrBuilder> auditBuilder_;
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     * @return Whether the audit field is set.
     */
    public boolean hasAudit() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     * @return The audit.
     */
    public com.josestg.pb.shared.audit.v1.Audit getAudit() {
      if (auditBuilder_ == null) {
        return audit_ == null ? com.josestg.pb.shared.audit.v1.Audit.getDefaultInstance() : audit_;
      } else {
        return auditBuilder_.getMessage();
      }
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     */
    public Builder setAudit(com.josestg.pb.shared.audit.v1.Audit value) {
      if (auditBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        audit_ = value;
      } else {
        auditBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     */
    public Builder setAudit(
        com.josestg.pb.shared.audit.v1.Audit.Builder builderForValue) {
      if (auditBuilder_ == null) {
        audit_ = builderForValue.build();
      } else {
        auditBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     */
    public Builder mergeAudit(com.josestg.pb.shared.audit.v1.Audit value) {
      if (auditBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          audit_ != null &&
          audit_ != com.josestg.pb.shared.audit.v1.Audit.getDefaultInstance()) {
          getAuditBuilder().mergeFrom(value);
        } else {
          audit_ = value;
        }
      } else {
        auditBuilder_.mergeFrom(value);
      }
      if (audit_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     */
    public Builder clearAudit() {
      bitField0_ = (bitField0_ & ~0x00000002);
      audit_ = null;
      if (auditBuilder_ != null) {
        auditBuilder_.dispose();
        auditBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     */
    public com.josestg.pb.shared.audit.v1.Audit.Builder getAuditBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetAuditFieldBuilder().getBuilder();
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     */
    public com.josestg.pb.shared.audit.v1.AuditOrBuilder getAuditOrBuilder() {
      if (auditBuilder_ != null) {
        return auditBuilder_.getMessageOrBuilder();
      } else {
        return audit_ == null ?
            com.josestg.pb.shared.audit.v1.Audit.getDefaultInstance() : audit_;
      }
    }
    /**
     * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.shared.audit.v1.Audit, com.josestg.pb.shared.audit.v1.Audit.Builder, com.josestg.pb.shared.audit.v1.AuditOrBuilder> 
        internalGetAuditFieldBuilder() {
      if (auditBuilder_ == null) {
        auditBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.josestg.pb.shared.audit.v1.Audit, com.josestg.pb.shared.audit.v1.Audit.Builder, com.josestg.pb.shared.audit.v1.AuditOrBuilder>(
                getAudit(),
                getParentForChildren(),
                isClean());
        audit_ = null;
      }
      return auditBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:team.project.feature.v1.ExampleRequest)
  }

  // @@protoc_insertion_point(class_scope:team.project.feature.v1.ExampleRequest)
  private static final com.josestg.pb.team.project.feature.v1.ExampleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.team.project.feature.v1.ExampleRequest();
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExampleRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExampleRequest>() {
    @java.lang.Override
    public ExampleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExampleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExampleRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.team.project.feature.v1.ExampleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

