// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: team/project/feature/v1/example.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.team.project.feature.v1;

@com.google.protobuf.Generated
public interface ExampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:team.project.feature.v1.ExampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
   * @return Whether the someTime field is set.
   */
  boolean hasSomeTime();
  /**
   * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
   * @return The someTime.
   */
  com.google.protobuf.Timestamp getSomeTime();
  /**
   * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getSomeTimeOrBuilder();
}
