// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: team/project/feature/v1/example.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.team.project.feature.v1;

@com.google.protobuf.Generated
public final class Example extends com.google.protobuf.GeneratedFile {
  private Example() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Example");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_team_project_feature_v1_ExampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_team_project_feature_v1_ExampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_team_project_feature_v1_ExampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_team_project_feature_v1_ExampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%team/project/feature/v1/example.proto\022" +
      "\027team.project.feature.v1\032\034google/api/ann" +
      "otations.proto\032\037google/protobuf/timestam" +
      "p.proto\032!identity/session/v1/session.pro" +
      "to\032\033shared/audit/v1/audit.proto\"z\n\016Examp" +
      "leRequest\022:\n\006create\030\001 \001(\0132\".identity.ses" +
      "sion.v1.CreateRequestR\006create\022,\n\005audit\030\002" +
      " \001(\0132\026.shared.audit.v1.AuditR\005audit\"K\n\017E" +
      "xampleResponse\0228\n\tsome_time\030\003 \001(\0132\032.goog" +
      "le.protobuf.TimestampR\tsome_time2\230\001\n\016Exa" +
      "mpleService\022\205\001\n\007Example\022\'.team.project.f" +
      "eature.v1.ExampleRequest\032(.team.project." +
      "feature.v1.ExampleResponse\"\'\202\323\344\223\002!\"\034/tea" +
      "m-project/api/v1/feature:\001*Bf\n&com.joses" +
      "tg.pb.team.project.feature.v1P\001Z:github." +
      "com/josestg/pb/go/team/project/feature/v" +
      "1;featurepbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.josestg.pb.session.v1.Session.getDescriptor(),
          com.josestg.pb.shared.audit.v1.AuditOuterClass.getDescriptor(),
        });
    internal_static_team_project_feature_v1_ExampleRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_team_project_feature_v1_ExampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_team_project_feature_v1_ExampleRequest_descriptor,
        new java.lang.String[] { "Create", "Audit", });
    internal_static_team_project_feature_v1_ExampleResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_team_project_feature_v1_ExampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_team_project_feature_v1_ExampleResponse_descriptor,
        new java.lang.String[] { "SomeTime", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.josestg.pb.session.v1.Session.getDescriptor();
    com.josestg.pb.shared.audit.v1.AuditOuterClass.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
