// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: team/project/feature/v1/example.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.team.project.feature.v1;

@com.google.protobuf.Generated
public interface ExampleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:team.project.feature.v1.ExampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
   * @return Whether the create field is set.
   */
  boolean hasCreate();
  /**
   * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
   * @return The create.
   */
  com.josestg.pb.session.v1.CreateRequest getCreate();
  /**
   * <code>.identity.session.v1.CreateRequest create = 1 [json_name = "create"];</code>
   */
  com.josestg.pb.session.v1.CreateRequestOrBuilder getCreateOrBuilder();

  /**
   * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
   * @return Whether the audit field is set.
   */
  boolean hasAudit();
  /**
   * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
   * @return The audit.
   */
  com.josestg.pb.shared.audit.v1.Audit getAudit();
  /**
   * <code>.shared.audit.v1.Audit audit = 2 [json_name = "audit"];</code>
   */
  com.josestg.pb.shared.audit.v1.AuditOrBuilder getAuditOrBuilder();
}
