// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: team/project/feature/v1/example.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.team.project.feature.v1;

/**
 * Protobuf type {@code team.project.feature.v1.ExampleResponse}
 */
@com.google.protobuf.Generated
public final class ExampleResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:team.project.feature.v1.ExampleResponse)
    ExampleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ExampleResponse");
  }
  // Use ExampleResponse.newBuilder() to construct.
  private ExampleResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExampleResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.team.project.feature.v1.ExampleResponse.class, com.josestg.pb.team.project.feature.v1.ExampleResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SOME_TIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp someTime_;
  /**
   * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
   * @return Whether the someTime field is set.
   */
  @java.lang.Override
  public boolean hasSomeTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
   * @return The someTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getSomeTime() {
    return someTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : someTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getSomeTimeOrBuilder() {
    return someTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : someTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getSomeTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSomeTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.team.project.feature.v1.ExampleResponse)) {
      return super.equals(obj);
    }
    com.josestg.pb.team.project.feature.v1.ExampleResponse other = (com.josestg.pb.team.project.feature.v1.ExampleResponse) obj;

    if (hasSomeTime() != other.hasSomeTime()) return false;
    if (hasSomeTime()) {
      if (!getSomeTime()
          .equals(other.getSomeTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSomeTime()) {
      hash = (37 * hash) + SOME_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getSomeTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.team.project.feature.v1.ExampleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.team.project.feature.v1.ExampleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code team.project.feature.v1.ExampleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:team.project.feature.v1.ExampleResponse)
      com.josestg.pb.team.project.feature.v1.ExampleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.team.project.feature.v1.ExampleResponse.class, com.josestg.pb.team.project.feature.v1.ExampleResponse.Builder.class);
    }

    // Construct using com.josestg.pb.team.project.feature.v1.ExampleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSomeTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      someTime_ = null;
      if (someTimeBuilder_ != null) {
        someTimeBuilder_.dispose();
        someTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.team.project.feature.v1.Example.internal_static_team_project_feature_v1_ExampleResponse_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.team.project.feature.v1.ExampleResponse getDefaultInstanceForType() {
      return com.josestg.pb.team.project.feature.v1.ExampleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.team.project.feature.v1.ExampleResponse build() {
      com.josestg.pb.team.project.feature.v1.ExampleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.team.project.feature.v1.ExampleResponse buildPartial() {
      com.josestg.pb.team.project.feature.v1.ExampleResponse result = new com.josestg.pb.team.project.feature.v1.ExampleResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.josestg.pb.team.project.feature.v1.ExampleResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.someTime_ = someTimeBuilder_ == null
            ? someTime_
            : someTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.team.project.feature.v1.ExampleResponse) {
        return mergeFrom((com.josestg.pb.team.project.feature.v1.ExampleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.team.project.feature.v1.ExampleResponse other) {
      if (other == com.josestg.pb.team.project.feature.v1.ExampleResponse.getDefaultInstance()) return this;
      if (other.hasSomeTime()) {
        mergeSomeTime(other.getSomeTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 26: {
              input.readMessage(
                  internalGetSomeTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp someTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> someTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     * @return Whether the someTime field is set.
     */
    public boolean hasSomeTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     * @return The someTime.
     */
    public com.google.protobuf.Timestamp getSomeTime() {
      if (someTimeBuilder_ == null) {
        return someTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : someTime_;
      } else {
        return someTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     */
    public Builder setSomeTime(com.google.protobuf.Timestamp value) {
      if (someTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        someTime_ = value;
      } else {
        someTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     */
    public Builder setSomeTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (someTimeBuilder_ == null) {
        someTime_ = builderForValue.build();
      } else {
        someTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     */
    public Builder mergeSomeTime(com.google.protobuf.Timestamp value) {
      if (someTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          someTime_ != null &&
          someTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getSomeTimeBuilder().mergeFrom(value);
        } else {
          someTime_ = value;
        }
      } else {
        someTimeBuilder_.mergeFrom(value);
      }
      if (someTime_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     */
    public Builder clearSomeTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      someTime_ = null;
      if (someTimeBuilder_ != null) {
        someTimeBuilder_.dispose();
        someTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getSomeTimeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetSomeTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSomeTimeOrBuilder() {
      if (someTimeBuilder_ != null) {
        return someTimeBuilder_.getMessageOrBuilder();
      } else {
        return someTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : someTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp some_time = 3 [json_name = "some_time"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetSomeTimeFieldBuilder() {
      if (someTimeBuilder_ == null) {
        someTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSomeTime(),
                getParentForChildren(),
                isClean());
        someTime_ = null;
      }
      return someTimeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:team.project.feature.v1.ExampleResponse)
  }

  // @@protoc_insertion_point(class_scope:team.project.feature.v1.ExampleResponse)
  private static final com.josestg.pb.team.project.feature.v1.ExampleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.team.project.feature.v1.ExampleResponse();
  }

  public static com.josestg.pb.team.project.feature.v1.ExampleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExampleResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExampleResponse>() {
    @java.lang.Override
    public ExampleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExampleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExampleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.team.project.feature.v1.ExampleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

