// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: shared/audit/v1/audit.proto

package auditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Audit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_shared_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_shared_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_shared_audit_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *Audit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Audit) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Audit) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_shared_audit_v1_audit_proto protoreflect.FileDescriptor

const file_shared_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x1bshared/audit/v1/audit.proto\x12\x0fshared.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\x05Audit\x12:\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\x12?\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"deleted_at\x88\x01\x01B\r\n" +
	"\v_deleted_atBT\n" +
	"\x1ecom.josestg.pb.shared.audit.v1P\x01Z0github.com/josestg/pb/go/shared/audit/v1;auditpbb\x06proto3"

var (
	file_shared_audit_v1_audit_proto_rawDescOnce sync.Once
	file_shared_audit_v1_audit_proto_rawDescData []byte
)

func file_shared_audit_v1_audit_proto_rawDescGZIP() []byte {
	file_shared_audit_v1_audit_proto_rawDescOnce.Do(func() {
		file_shared_audit_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_audit_v1_audit_proto_rawDesc), len(file_shared_audit_v1_audit_proto_rawDesc)))
	})
	return file_shared_audit_v1_audit_proto_rawDescData
}

var file_shared_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_audit_v1_audit_proto_goTypes = []any{
	(*Audit)(nil),                 // 0: shared.audit.v1.Audit
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_shared_audit_v1_audit_proto_depIdxs = []int32{
	1, // 0: shared.audit.v1.Audit.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: shared.audit.v1.Audit.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: shared.audit.v1.Audit.deleted_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shared_audit_v1_audit_proto_init() }
func file_shared_audit_v1_audit_proto_init() {
	if File_shared_audit_v1_audit_proto != nil {
		return
	}
	file_shared_audit_v1_audit_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_audit_v1_audit_proto_rawDesc), len(file_shared_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_shared_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_shared_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_shared_audit_v1_audit_proto = out.File
	file_shared_audit_v1_audit_proto_goTypes = nil
	file_shared_audit_v1_audit_proto_depIdxs = nil
}
