// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: payment/currency/v1/currency.proto

package currencypb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_payment_currency_v1_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_payment_currency_v1_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_payment_currency_v1_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Pair) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Pair) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

type ExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*Pair                `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=requested_at,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_payment_currency_v1_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_currency_v1_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_payment_currency_v1_currency_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeRequest) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *ExchangeRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_payment_currency_v1_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_payment_currency_v1_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_payment_currency_v1_currency_proto_rawDescGZIP(), []int{2}
}

func (x *Rate) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *Rate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Rate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*Rate                `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	RespondedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=responded_at,proto3" json:"responded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_payment_currency_v1_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_currency_v1_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_payment_currency_v1_currency_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeResponse) GetRates() []*Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *ExchangeResponse) GetRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondedAt
	}
	return nil
}

var File_payment_currency_v1_currency_proto protoreflect.FileDescriptor

const file_payment_currency_v1_currency_proto_rawDesc = "" +
	"\n" +
	"\"payment/currency/v1/currency.proto\x12\x13payment.currency.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x04Pair\x12\x1f\n" +
	"\x04base\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x98\x01\x03R\x04base\x12!\n" +
	"\x05quote\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x98\x01\x03R\x05quote\"\x9c\x01\n" +
	"\x0fExchangeRequest\x12<\n" +
	"\x05pairs\x18\x01 \x03(\v2\x19.payment.currency.v1.PairB\v\xbaH\b\xc8\x01\x01\x92\x01\x02\b\x01R\x05pairs\x12K\n" +
	"\frequested_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\v\xbaH\b\xc8\x01\x01\xb2\x01\x02@\x01R\frequested_at\"\x83\x01\n" +
	"\x04Rate\x12-\n" +
	"\x04pair\x18\x01 \x01(\v2\x19.payment.currency.v1.PairR\x04pair\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x83\x01\n" +
	"\x10ExchangeResponse\x12/\n" +
	"\x05rates\x18\x01 \x03(\v2\x19.payment.currency.v1.RateR\x05rates\x12>\n" +
	"\fresponded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fresponded_at2\xa3\x01\n" +
	"\x0fExchangeService\x12\x8f\x01\n" +
	"\bExchange\x12$.payment.currency.v1.ExchangeRequest\x1a%.payment.currency.v1.ExchangeResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/payment-service/api/v1/currencies/exchangeB_\n" +
	"\"com.josestg.pb.payment.currency.v1P\x01Z7github.com/josestg/pb/go/payment/currency/v1;currencypbb\x06proto3"

var (
	file_payment_currency_v1_currency_proto_rawDescOnce sync.Once
	file_payment_currency_v1_currency_proto_rawDescData []byte
)

func file_payment_currency_v1_currency_proto_rawDescGZIP() []byte {
	file_payment_currency_v1_currency_proto_rawDescOnce.Do(func() {
		file_payment_currency_v1_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_currency_v1_currency_proto_rawDesc), len(file_payment_currency_v1_currency_proto_rawDesc)))
	})
	return file_payment_currency_v1_currency_proto_rawDescData
}

var file_payment_currency_v1_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_currency_v1_currency_proto_goTypes = []any{
	(*Pair)(nil),                  // 0: payment.currency.v1.Pair
	(*ExchangeRequest)(nil),       // 1: payment.currency.v1.ExchangeRequest
	(*Rate)(nil),                  // 2: payment.currency.v1.Rate
	(*ExchangeResponse)(nil),      // 3: payment.currency.v1.ExchangeResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_payment_currency_v1_currency_proto_depIdxs = []int32{
	0, // 0: payment.currency.v1.ExchangeRequest.pairs:type_name -> payment.currency.v1.Pair
	4, // 1: payment.currency.v1.ExchangeRequest.requested_at:type_name -> google.protobuf.Timestamp
	0, // 2: payment.currency.v1.Rate.pair:type_name -> payment.currency.v1.Pair
	4, // 3: payment.currency.v1.Rate.timestamp:type_name -> google.protobuf.Timestamp
	2, // 4: payment.currency.v1.ExchangeResponse.rates:type_name -> payment.currency.v1.Rate
	4, // 5: payment.currency.v1.ExchangeResponse.responded_at:type_name -> google.protobuf.Timestamp
	1, // 6: payment.currency.v1.ExchangeService.Exchange:input_type -> payment.currency.v1.ExchangeRequest
	3, // 7: payment.currency.v1.ExchangeService.Exchange:output_type -> payment.currency.v1.ExchangeResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_payment_currency_v1_currency_proto_init() }
func file_payment_currency_v1_currency_proto_init() {
	if File_payment_currency_v1_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_currency_v1_currency_proto_rawDesc), len(file_payment_currency_v1_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_currency_v1_currency_proto_goTypes,
		DependencyIndexes: file_payment_currency_v1_currency_proto_depIdxs,
		MessageInfos:      file_payment_currency_v1_currency_proto_msgTypes,
	}.Build()
	File_payment_currency_v1_currency_proto = out.File
	file_payment_currency_v1_currency_proto_goTypes = nil
	file_payment_currency_v1_currency_proto_depIdxs = nil
}
