// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/session/v1/session.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.session.v1;

@com.google.protobuf.Generated
public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.session.v1.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 2 [json_name = "email", (.buf.validate.field) = { ... }</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2 [json_name = "email", (.buf.validate.field) = { ... }</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3 [json_name = "password", (.buf.validate.field) = { ... }</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3 [json_name = "password", (.buf.validate.field) = { ... }</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
