// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/session/v1/session.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.session.v1;

@com.google.protobuf.Generated
public interface CreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.session.v1.CreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
   * @return Whether the accessToken field is set.
   */
  boolean hasAccessToken();
  /**
   * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
   * @return The accessToken.
   */
  com.josestg.pb.identity.token.v1.Token getAccessToken();
  /**
   * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
   */
  com.josestg.pb.identity.token.v1.TokenOrBuilder getAccessTokenOrBuilder();

  /**
   * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
   * @return Whether the refreshToken field is set.
   */
  boolean hasRefreshToken();
  /**
   * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
   * @return The refreshToken.
   */
  com.josestg.pb.identity.token.v1.Token getRefreshToken();
  /**
   * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
   */
  com.josestg.pb.identity.token.v1.TokenOrBuilder getRefreshTokenOrBuilder();
}
