// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/session/v1/session.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.session.v1;

/**
 * Protobuf type {@code identity.session.v1.CreateResponse}
 */
@com.google.protobuf.Generated
public final class CreateResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:identity.session.v1.CreateResponse)
    CreateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "CreateResponse");
  }
  // Use CreateResponse.newBuilder() to construct.
  private CreateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_CreateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_CreateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.session.v1.CreateResponse.class, com.josestg.pb.session.v1.CreateResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ACCESS_TOKEN_FIELD_NUMBER = 1;
  private com.josestg.pb.identity.token.v1.Token accessToken_;
  /**
   * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
   * @return Whether the accessToken field is set.
   */
  @java.lang.Override
  public boolean hasAccessToken() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
   * @return The accessToken.
   */
  @java.lang.Override
  public com.josestg.pb.identity.token.v1.Token getAccessToken() {
    return accessToken_ == null ? com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : accessToken_;
  }
  /**
   * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
   */
  @java.lang.Override
  public com.josestg.pb.identity.token.v1.TokenOrBuilder getAccessTokenOrBuilder() {
    return accessToken_ == null ? com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : accessToken_;
  }

  public static final int REFRESH_TOKEN_FIELD_NUMBER = 2;
  private com.josestg.pb.identity.token.v1.Token refreshToken_;
  /**
   * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
   * @return Whether the refreshToken field is set.
   */
  @java.lang.Override
  public boolean hasRefreshToken() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
   * @return The refreshToken.
   */
  @java.lang.Override
  public com.josestg.pb.identity.token.v1.Token getRefreshToken() {
    return refreshToken_ == null ? com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : refreshToken_;
  }
  /**
   * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
   */
  @java.lang.Override
  public com.josestg.pb.identity.token.v1.TokenOrBuilder getRefreshTokenOrBuilder() {
    return refreshToken_ == null ? com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : refreshToken_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getAccessToken());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getRefreshToken());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAccessToken());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRefreshToken());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.session.v1.CreateResponse)) {
      return super.equals(obj);
    }
    com.josestg.pb.session.v1.CreateResponse other = (com.josestg.pb.session.v1.CreateResponse) obj;

    if (hasAccessToken() != other.hasAccessToken()) return false;
    if (hasAccessToken()) {
      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
    }
    if (hasRefreshToken() != other.hasRefreshToken()) return false;
    if (hasRefreshToken()) {
      if (!getRefreshToken()
          .equals(other.getRefreshToken())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAccessToken()) {
      hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
    }
    if (hasRefreshToken()) {
      hash = (37 * hash) + REFRESH_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRefreshToken().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.session.v1.CreateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.session.v1.CreateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.session.v1.CreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.session.v1.CreateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code identity.session.v1.CreateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:identity.session.v1.CreateResponse)
      com.josestg.pb.session.v1.CreateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_CreateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_CreateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.session.v1.CreateResponse.class, com.josestg.pb.session.v1.CreateResponse.Builder.class);
    }

    // Construct using com.josestg.pb.session.v1.CreateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetAccessTokenFieldBuilder();
        internalGetRefreshTokenFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accessToken_ = null;
      if (accessTokenBuilder_ != null) {
        accessTokenBuilder_.dispose();
        accessTokenBuilder_ = null;
      }
      refreshToken_ = null;
      if (refreshTokenBuilder_ != null) {
        refreshTokenBuilder_.dispose();
        refreshTokenBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_CreateResponse_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.session.v1.CreateResponse getDefaultInstanceForType() {
      return com.josestg.pb.session.v1.CreateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.session.v1.CreateResponse build() {
      com.josestg.pb.session.v1.CreateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.session.v1.CreateResponse buildPartial() {
      com.josestg.pb.session.v1.CreateResponse result = new com.josestg.pb.session.v1.CreateResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.josestg.pb.session.v1.CreateResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accessToken_ = accessTokenBuilder_ == null
            ? accessToken_
            : accessTokenBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.refreshToken_ = refreshTokenBuilder_ == null
            ? refreshToken_
            : refreshTokenBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.session.v1.CreateResponse) {
        return mergeFrom((com.josestg.pb.session.v1.CreateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.session.v1.CreateResponse other) {
      if (other == com.josestg.pb.session.v1.CreateResponse.getDefaultInstance()) return this;
      if (other.hasAccessToken()) {
        mergeAccessToken(other.getAccessToken());
      }
      if (other.hasRefreshToken()) {
        mergeRefreshToken(other.getRefreshToken());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetAccessTokenFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRefreshTokenFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.josestg.pb.identity.token.v1.Token accessToken_;
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.identity.token.v1.Token, com.josestg.pb.identity.token.v1.Token.Builder, com.josestg.pb.identity.token.v1.TokenOrBuilder> accessTokenBuilder_;
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     * @return Whether the accessToken field is set.
     */
    public boolean hasAccessToken() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     * @return The accessToken.
     */
    public com.josestg.pb.identity.token.v1.Token getAccessToken() {
      if (accessTokenBuilder_ == null) {
        return accessToken_ == null ? com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : accessToken_;
      } else {
        return accessTokenBuilder_.getMessage();
      }
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     */
    public Builder setAccessToken(com.josestg.pb.identity.token.v1.Token value) {
      if (accessTokenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accessToken_ = value;
      } else {
        accessTokenBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     */
    public Builder setAccessToken(
        com.josestg.pb.identity.token.v1.Token.Builder builderForValue) {
      if (accessTokenBuilder_ == null) {
        accessToken_ = builderForValue.build();
      } else {
        accessTokenBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     */
    public Builder mergeAccessToken(com.josestg.pb.identity.token.v1.Token value) {
      if (accessTokenBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          accessToken_ != null &&
          accessToken_ != com.josestg.pb.identity.token.v1.Token.getDefaultInstance()) {
          getAccessTokenBuilder().mergeFrom(value);
        } else {
          accessToken_ = value;
        }
      } else {
        accessTokenBuilder_.mergeFrom(value);
      }
      if (accessToken_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     */
    public Builder clearAccessToken() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accessToken_ = null;
      if (accessTokenBuilder_ != null) {
        accessTokenBuilder_.dispose();
        accessTokenBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     */
    public com.josestg.pb.identity.token.v1.Token.Builder getAccessTokenBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetAccessTokenFieldBuilder().getBuilder();
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     */
    public com.josestg.pb.identity.token.v1.TokenOrBuilder getAccessTokenOrBuilder() {
      if (accessTokenBuilder_ != null) {
        return accessTokenBuilder_.getMessageOrBuilder();
      } else {
        return accessToken_ == null ?
            com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : accessToken_;
      }
    }
    /**
     * <code>.identity.token.v1.Token access_token = 1 [json_name = "access_token"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.identity.token.v1.Token, com.josestg.pb.identity.token.v1.Token.Builder, com.josestg.pb.identity.token.v1.TokenOrBuilder> 
        internalGetAccessTokenFieldBuilder() {
      if (accessTokenBuilder_ == null) {
        accessTokenBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.josestg.pb.identity.token.v1.Token, com.josestg.pb.identity.token.v1.Token.Builder, com.josestg.pb.identity.token.v1.TokenOrBuilder>(
                getAccessToken(),
                getParentForChildren(),
                isClean());
        accessToken_ = null;
      }
      return accessTokenBuilder_;
    }

    private com.josestg.pb.identity.token.v1.Token refreshToken_;
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.identity.token.v1.Token, com.josestg.pb.identity.token.v1.Token.Builder, com.josestg.pb.identity.token.v1.TokenOrBuilder> refreshTokenBuilder_;
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     * @return Whether the refreshToken field is set.
     */
    public boolean hasRefreshToken() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     * @return The refreshToken.
     */
    public com.josestg.pb.identity.token.v1.Token getRefreshToken() {
      if (refreshTokenBuilder_ == null) {
        return refreshToken_ == null ? com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : refreshToken_;
      } else {
        return refreshTokenBuilder_.getMessage();
      }
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     */
    public Builder setRefreshToken(com.josestg.pb.identity.token.v1.Token value) {
      if (refreshTokenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        refreshToken_ = value;
      } else {
        refreshTokenBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     */
    public Builder setRefreshToken(
        com.josestg.pb.identity.token.v1.Token.Builder builderForValue) {
      if (refreshTokenBuilder_ == null) {
        refreshToken_ = builderForValue.build();
      } else {
        refreshTokenBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     */
    public Builder mergeRefreshToken(com.josestg.pb.identity.token.v1.Token value) {
      if (refreshTokenBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          refreshToken_ != null &&
          refreshToken_ != com.josestg.pb.identity.token.v1.Token.getDefaultInstance()) {
          getRefreshTokenBuilder().mergeFrom(value);
        } else {
          refreshToken_ = value;
        }
      } else {
        refreshTokenBuilder_.mergeFrom(value);
      }
      if (refreshToken_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     */
    public Builder clearRefreshToken() {
      bitField0_ = (bitField0_ & ~0x00000002);
      refreshToken_ = null;
      if (refreshTokenBuilder_ != null) {
        refreshTokenBuilder_.dispose();
        refreshTokenBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     */
    public com.josestg.pb.identity.token.v1.Token.Builder getRefreshTokenBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRefreshTokenFieldBuilder().getBuilder();
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     */
    public com.josestg.pb.identity.token.v1.TokenOrBuilder getRefreshTokenOrBuilder() {
      if (refreshTokenBuilder_ != null) {
        return refreshTokenBuilder_.getMessageOrBuilder();
      } else {
        return refreshToken_ == null ?
            com.josestg.pb.identity.token.v1.Token.getDefaultInstance() : refreshToken_;
      }
    }
    /**
     * <code>.identity.token.v1.Token refresh_token = 2 [json_name = "refresh_token"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.identity.token.v1.Token, com.josestg.pb.identity.token.v1.Token.Builder, com.josestg.pb.identity.token.v1.TokenOrBuilder> 
        internalGetRefreshTokenFieldBuilder() {
      if (refreshTokenBuilder_ == null) {
        refreshTokenBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.josestg.pb.identity.token.v1.Token, com.josestg.pb.identity.token.v1.Token.Builder, com.josestg.pb.identity.token.v1.TokenOrBuilder>(
                getRefreshToken(),
                getParentForChildren(),
                isClean());
        refreshToken_ = null;
      }
      return refreshTokenBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:identity.session.v1.CreateResponse)
  }

  // @@protoc_insertion_point(class_scope:identity.session.v1.CreateResponse)
  private static final com.josestg.pb.session.v1.CreateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.session.v1.CreateResponse();
  }

  public static com.josestg.pb.session.v1.CreateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateResponse>() {
    @java.lang.Override
    public CreateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.session.v1.CreateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

