// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/session/v1/session.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.session.v1;

@com.google.protobuf.Generated
public interface RevokeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identity.session.v1.RevokeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The jti.
   */
  java.lang.String getJti();
  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The bytes for jti.
   */
  com.google.protobuf.ByteString
      getJtiBytes();

  /**
   * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the revokedAt field is set.
   */
  boolean hasRevokedAt();
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
   * @return The revokedAt.
   */
  com.google.protobuf.Timestamp getRevokedAt();
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder();
}
