// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/session/v1/session.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.session.v1;

/**
 * Protobuf type {@code identity.session.v1.RevokeResponse}
 */
@com.google.protobuf.Generated
public final class RevokeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:identity.session.v1.RevokeResponse)
    RevokeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "RevokeResponse");
  }
  // Use RevokeResponse.newBuilder() to construct.
  private RevokeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RevokeResponse() {
    jti_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_RevokeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_RevokeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.session.v1.RevokeResponse.class, com.josestg.pb.session.v1.RevokeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int JTI_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jti_ = "";
  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The jti.
   */
  @java.lang.Override
  public java.lang.String getJti() {
    java.lang.Object ref = jti_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jti_ = s;
      return s;
    }
  }
  /**
   * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
   * @return The bytes for jti.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJtiBytes() {
    java.lang.Object ref = jti_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jti_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REVOKED_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp revokedAt_;
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the revokedAt field is set.
   */
  @java.lang.Override
  public boolean hasRevokedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
   * @return The revokedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRevokedAt() {
    return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder() {
    return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jti_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, jti_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getRevokedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jti_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, jti_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRevokedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.session.v1.RevokeResponse)) {
      return super.equals(obj);
    }
    com.josestg.pb.session.v1.RevokeResponse other = (com.josestg.pb.session.v1.RevokeResponse) obj;

    if (!getJti()
        .equals(other.getJti())) return false;
    if (hasRevokedAt() != other.hasRevokedAt()) return false;
    if (hasRevokedAt()) {
      if (!getRevokedAt()
          .equals(other.getRevokedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JTI_FIELD_NUMBER;
    hash = (53 * hash) + getJti().hashCode();
    if (hasRevokedAt()) {
      hash = (37 * hash) + REVOKED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getRevokedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.session.v1.RevokeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.session.v1.RevokeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.session.v1.RevokeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.session.v1.RevokeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code identity.session.v1.RevokeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:identity.session.v1.RevokeResponse)
      com.josestg.pb.session.v1.RevokeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_RevokeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_RevokeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.session.v1.RevokeResponse.class, com.josestg.pb.session.v1.RevokeResponse.Builder.class);
    }

    // Construct using com.josestg.pb.session.v1.RevokeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRevokedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jti_ = "";
      revokedAt_ = null;
      if (revokedAtBuilder_ != null) {
        revokedAtBuilder_.dispose();
        revokedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.session.v1.Session.internal_static_identity_session_v1_RevokeResponse_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.session.v1.RevokeResponse getDefaultInstanceForType() {
      return com.josestg.pb.session.v1.RevokeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.session.v1.RevokeResponse build() {
      com.josestg.pb.session.v1.RevokeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.session.v1.RevokeResponse buildPartial() {
      com.josestg.pb.session.v1.RevokeResponse result = new com.josestg.pb.session.v1.RevokeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.josestg.pb.session.v1.RevokeResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jti_ = jti_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.revokedAt_ = revokedAtBuilder_ == null
            ? revokedAt_
            : revokedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.session.v1.RevokeResponse) {
        return mergeFrom((com.josestg.pb.session.v1.RevokeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.session.v1.RevokeResponse other) {
      if (other == com.josestg.pb.session.v1.RevokeResponse.getDefaultInstance()) return this;
      if (!other.getJti().isEmpty()) {
        jti_ = other.jti_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasRevokedAt()) {
        mergeRevokedAt(other.getRevokedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jti_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRevokedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object jti_ = "";
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @return The jti.
     */
    public java.lang.String getJti() {
      java.lang.Object ref = jti_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jti_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @return The bytes for jti.
     */
    public com.google.protobuf.ByteString
        getJtiBytes() {
      java.lang.Object ref = jti_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jti_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @param value The jti to set.
     * @return This builder for chaining.
     */
    public Builder setJti(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jti_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearJti() {
      jti_ = getDefaultInstance().getJti();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string jti = 1 [json_name = "jti", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for jti to set.
     * @return This builder for chaining.
     */
    public Builder setJtiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jti_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp revokedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> revokedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     * @return Whether the revokedAt field is set.
     */
    public boolean hasRevokedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     * @return The revokedAt.
     */
    public com.google.protobuf.Timestamp getRevokedAt() {
      if (revokedAtBuilder_ == null) {
        return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
      } else {
        return revokedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setRevokedAt(com.google.protobuf.Timestamp value) {
      if (revokedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        revokedAt_ = value;
      } else {
        revokedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setRevokedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (revokedAtBuilder_ == null) {
        revokedAt_ = builderForValue.build();
      } else {
        revokedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeRevokedAt(com.google.protobuf.Timestamp value) {
      if (revokedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          revokedAt_ != null &&
          revokedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRevokedAtBuilder().mergeFrom(value);
        } else {
          revokedAt_ = value;
        }
      } else {
        revokedAtBuilder_.mergeFrom(value);
      }
      if (revokedAt_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearRevokedAt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      revokedAt_ = null;
      if (revokedAtBuilder_ != null) {
        revokedAtBuilder_.dispose();
        revokedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getRevokedAtBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRevokedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder() {
      if (revokedAtBuilder_ != null) {
        return revokedAtBuilder_.getMessageOrBuilder();
      } else {
        return revokedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 2 [json_name = "revoked_at", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetRevokedAtFieldBuilder() {
      if (revokedAtBuilder_ == null) {
        revokedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRevokedAt(),
                getParentForChildren(),
                isClean());
        revokedAt_ = null;
      }
      return revokedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:identity.session.v1.RevokeResponse)
  }

  // @@protoc_insertion_point(class_scope:identity.session.v1.RevokeResponse)
  private static final com.josestg.pb.session.v1.RevokeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.session.v1.RevokeResponse();
  }

  public static com.josestg.pb.session.v1.RevokeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RevokeResponse>
      PARSER = new com.google.protobuf.AbstractParser<RevokeResponse>() {
    @java.lang.Override
    public RevokeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RevokeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RevokeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.session.v1.RevokeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

