// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: identity/session/v1/session.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.session.v1;

@com.google.protobuf.Generated
public final class Session extends com.google.protobuf.GeneratedFile {
  private Session() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Session");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_session_v1_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_identity_session_v1_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_session_v1_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_identity_session_v1_CreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_session_v1_RevokeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_identity_session_v1_RevokeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identity_session_v1_RevokeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_identity_session_v1_RevokeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!identity/session/v1/session.proto\022\023ide" +
      "ntity.session.v1\032\037google/protobuf/timest" +
      "amp.proto\032\035identity/token/v1/token.proto" +
      "\032\033buf/validate/validate.proto\"}\n\rCreateR" +
      "equest\022 \n\004name\030\001 \001(\tB\014\272H\tr\004\020\002\030x\310\001\001R\004name" +
      "\022 \n\005email\030\002 \001(\tB\n\272H\007r\002`\001\310\001\001R\005email\022(\n\010pa" +
      "ssword\030\003 \001(\tB\014\272H\tr\004\020\010\030@\310\001\001R\010password\"\216\001\n" +
      "\016CreateResponse\022<\n\014access_token\030\001 \001(\0132\030." +
      "identity.token.v1.TokenR\014access_token\022>\n" +
      "\rrefresh_token\030\002 \001(\0132\030.identity.token.v1" +
      ".TokenR\rrefresh_token\"\215\001\n\rRevokeRequest\022" +
      "<\n\014access_token\030\001 \001(\0132\030.identity.token.v" +
      "1.TokenR\014access_token\022>\n\rrefresh_token\030\002" +
      " \001(\0132\030.identity.token.v1.TokenR\rrefresh_" +
      "token\"x\n\016RevokeResponse\022\035\n\003jti\030\001 \001(\tB\013\272H" +
      "\010r\003\210\002\001\310\001\001R\003jti\022G\n\nrevoked_at\030\002 \001(\0132\032.goo" +
      "gle.protobuf.TimestampB\013\272H\010\262\001\002@\001\310\001\001R\nrev" +
      "oked_at2d\n\rCreateService\022S\n\006Create\022\".ide" +
      "ntity.session.v1.CreateRequest\032#.identit" +
      "y.session.v1.CreateResponse\"\0002d\n\rRevokeS" +
      "ervice\022S\n\006Revoke\022\".identity.session.v1.R" +
      "evokeRequest\032#.identity.session.v1.Revok" +
      "eResponse\"\000BU\n\031com.josestg.pb.session.v1" +
      "P\001Z6github.com/josestg/pb/go/identity/se" +
      "ssion/v1;sessionpbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.josestg.pb.identity.token.v1.TokenOuterClass.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_identity_session_v1_CreateRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_identity_session_v1_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_identity_session_v1_CreateRequest_descriptor,
        new java.lang.String[] { "Name", "Email", "Password", });
    internal_static_identity_session_v1_CreateResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_identity_session_v1_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_identity_session_v1_CreateResponse_descriptor,
        new java.lang.String[] { "AccessToken", "RefreshToken", });
    internal_static_identity_session_v1_RevokeRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_identity_session_v1_RevokeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_identity_session_v1_RevokeRequest_descriptor,
        new java.lang.String[] { "AccessToken", "RefreshToken", });
    internal_static_identity_session_v1_RevokeResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_identity_session_v1_RevokeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_identity_session_v1_RevokeResponse_descriptor,
        new java.lang.String[] { "Jti", "RevokedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.josestg.pb.identity.token.v1.TokenOuterClass.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
