// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: identity/token/v1/token.proto

package tokenpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jti           string                 `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,proto3" json:"issued_at,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expired_at,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_identity_token_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_identity_token_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_identity_token_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *Token) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Token) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Token) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

var File_identity_token_v1_token_proto protoreflect.FileDescriptor

const file_identity_token_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x1didentity/token/v1/token.proto\x12\x11identity.token.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xca\x01\n" +
	"\x05Token\x12\x1d\n" +
	"\x03jti\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x88\x02\x01R\x03jti\x12\x1c\n" +
	"\x05value\x18\x02 \x01(\fB\x06\xbaH\x03\xc8\x01\x01R\x05value\x12@\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tissued_at\x12B\n" +
	"\n" +
	"expired_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"expired_atBX\n" +
	" com.josestg.pb.identity.token.v1P\x01Z2github.com/josestg/pb/go/identity/token/v1;tokenpbb\x06proto3"

var (
	file_identity_token_v1_token_proto_rawDescOnce sync.Once
	file_identity_token_v1_token_proto_rawDescData []byte
)

func file_identity_token_v1_token_proto_rawDescGZIP() []byte {
	file_identity_token_v1_token_proto_rawDescOnce.Do(func() {
		file_identity_token_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_token_v1_token_proto_rawDesc), len(file_identity_token_v1_token_proto_rawDesc)))
	})
	return file_identity_token_v1_token_proto_rawDescData
}

var file_identity_token_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_identity_token_v1_token_proto_goTypes = []any{
	(*Token)(nil),                 // 0: identity.token.v1.Token
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_identity_token_v1_token_proto_depIdxs = []int32{
	1, // 0: identity.token.v1.Token.issued_at:type_name -> google.protobuf.Timestamp
	1, // 1: identity.token.v1.Token.expired_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_token_v1_token_proto_init() }
func file_identity_token_v1_token_proto_init() {
	if File_identity_token_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_token_v1_token_proto_rawDesc), len(file_identity_token_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_token_v1_token_proto_goTypes,
		DependencyIndexes: file_identity_token_v1_token_proto_depIdxs,
		MessageInfos:      file_identity_token_v1_token_proto_msgTypes,
	}.Build()
	File_identity_token_v1_token_proto = out.File
	file_identity_token_v1_token_proto_goTypes = nil
	file_identity_token_v1_token_proto_depIdxs = nil
}
