// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

@com.google.protobuf.Generated
public final class Currency extends com.google.protobuf.GeneratedFile {
  private Currency() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Currency");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_currency_v1_Pair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_payment_currency_v1_Pair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_currency_v1_ExchangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_payment_currency_v1_ExchangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_currency_v1_Rate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_payment_currency_v1_Rate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_currency_v1_ExchangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_payment_currency_v1_ExchangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"payment/currency/v1/currency.proto\022\023pa" +
      "yment.currency.v1\032\033buf/validate/validate" +
      ".proto\032\034google/api/annotations.proto\032\037go" +
      "ogle/protobuf/timestamp.proto\"J\n\004Pair\022\037\n" +
      "\004base\030\001 \001(\tB\013\272H\010r\003\230\001\003\310\001\001R\004base\022!\n\005quote\030" +
      "\002 \001(\tB\013\272H\010r\003\230\001\003\310\001\001R\005quote\"\234\001\n\017ExchangeRe" +
      "quest\022<\n\005pairs\030\001 \003(\0132\031.payment.currency." +
      "v1.PairB\013\272H\010\222\001\002\010\001\310\001\001R\005pairs\022K\n\014requested" +
      "_at\030\002 \001(\0132\032.google.protobuf.TimestampB\013\272" +
      "H\010\262\001\002@\001\310\001\001R\014requested_at\"\203\001\n\004Rate\022-\n\004pai" +
      "r\030\001 \001(\0132\031.payment.currency.v1.PairR\004pair" +
      "\022\022\n\004rate\030\002 \001(\001R\004rate\0228\n\ttimestamp\030\003 \001(\0132" +
      "\032.google.protobuf.TimestampR\ttimestamp\"\203" +
      "\001\n\020ExchangeResponse\022/\n\005rates\030\001 \003(\0132\031.pay" +
      "ment.currency.v1.RateR\005rates\022>\n\014responde" +
      "d_at\030\002 \001(\0132\032.google.protobuf.TimestampR\014" +
      "responded_at2\243\001\n\017ExchangeService\022\217\001\n\010Exc" +
      "hange\022$.payment.currency.v1.ExchangeRequ" +
      "est\032%.payment.currency.v1.ExchangeRespon" +
      "se\"6\202\323\344\223\0020\"+/payment-service/api/v1/curr" +
      "encies/exchange:\001*B_\n\"com.josestg.pb.pay" +
      "ment.currency.v1P\001Z7github.com/josestg/p" +
      "b/go/payment/currency/v1;currencypbb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_payment_currency_v1_Pair_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_payment_currency_v1_Pair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_payment_currency_v1_Pair_descriptor,
        new java.lang.String[] { "Base", "Quote", });
    internal_static_payment_currency_v1_ExchangeRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_payment_currency_v1_ExchangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_payment_currency_v1_ExchangeRequest_descriptor,
        new java.lang.String[] { "Pairs", "RequestedAt", });
    internal_static_payment_currency_v1_Rate_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_payment_currency_v1_Rate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_payment_currency_v1_Rate_descriptor,
        new java.lang.String[] { "Pair", "Rate", "Timestamp", });
    internal_static_payment_currency_v1_ExchangeResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_payment_currency_v1_ExchangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_payment_currency_v1_ExchangeResponse_descriptor,
        new java.lang.String[] { "Rates", "RespondedAt", });
    descriptor.resolveAllFeaturesImmutable();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
