// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

@com.google.protobuf.Generated
public interface ExchangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payment.currency.v1.ExchangeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  java.util.List<com.josestg.pb.payment.currency.v1.Rate> 
      getRatesList();
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  com.josestg.pb.payment.currency.v1.Rate getRates(int index);
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  int getRatesCount();
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  java.util.List<? extends com.josestg.pb.payment.currency.v1.RateOrBuilder> 
      getRatesOrBuilderList();
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  com.josestg.pb.payment.currency.v1.RateOrBuilder getRatesOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
   * @return Whether the respondedAt field is set.
   */
  boolean hasRespondedAt();
  /**
   * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
   * @return The respondedAt.
   */
  com.google.protobuf.Timestamp getRespondedAt();
  /**
   * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getRespondedAtOrBuilder();
}
