// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

@com.google.protobuf.Generated
public interface ExchangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payment.currency.v1.ExchangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<com.josestg.pb.payment.currency.v1.Pair> 
      getPairsList();
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  com.josestg.pb.payment.currency.v1.Pair getPairs(int index);
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  int getPairsCount();
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<? extends com.josestg.pb.payment.currency.v1.PairOrBuilder> 
      getPairsOrBuilderList();
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  com.josestg.pb.payment.currency.v1.PairOrBuilder getPairsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the requestedAt field is set.
   */
  boolean hasRequestedAt();
  /**
   * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
   * @return The requestedAt.
   */
  com.google.protobuf.Timestamp getRequestedAt();
  /**
   * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getRequestedAtOrBuilder();
}
