// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

/**
 * Protobuf type {@code payment.currency.v1.ExchangeResponse}
 */
@com.google.protobuf.Generated
public final class ExchangeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:payment.currency.v1.ExchangeResponse)
    ExchangeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ExchangeResponse");
  }
  // Use ExchangeResponse.newBuilder() to construct.
  private ExchangeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExchangeResponse() {
    rates_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.payment.currency.v1.ExchangeResponse.class, com.josestg.pb.payment.currency.v1.ExchangeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RATES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.josestg.pb.payment.currency.v1.Rate> rates_;
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  @java.lang.Override
  public java.util.List<com.josestg.pb.payment.currency.v1.Rate> getRatesList() {
    return rates_;
  }
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.josestg.pb.payment.currency.v1.RateOrBuilder> 
      getRatesOrBuilderList() {
    return rates_;
  }
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  @java.lang.Override
  public int getRatesCount() {
    return rates_.size();
  }
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.Rate getRates(int index) {
    return rates_.get(index);
  }
  /**
   * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
   */
  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.RateOrBuilder getRatesOrBuilder(
      int index) {
    return rates_.get(index);
  }

  public static final int RESPONDED_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp respondedAt_;
  /**
   * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
   * @return Whether the respondedAt field is set.
   */
  @java.lang.Override
  public boolean hasRespondedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
   * @return The respondedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRespondedAt() {
    return respondedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : respondedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRespondedAtOrBuilder() {
    return respondedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : respondedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rates_.size(); i++) {
      output.writeMessage(1, rates_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getRespondedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rates_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRespondedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.payment.currency.v1.ExchangeResponse)) {
      return super.equals(obj);
    }
    com.josestg.pb.payment.currency.v1.ExchangeResponse other = (com.josestg.pb.payment.currency.v1.ExchangeResponse) obj;

    if (!getRatesList()
        .equals(other.getRatesList())) return false;
    if (hasRespondedAt() != other.hasRespondedAt()) return false;
    if (hasRespondedAt()) {
      if (!getRespondedAt()
          .equals(other.getRespondedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRatesCount() > 0) {
      hash = (37 * hash) + RATES_FIELD_NUMBER;
      hash = (53 * hash) + getRatesList().hashCode();
    }
    if (hasRespondedAt()) {
      hash = (37 * hash) + RESPONDED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getRespondedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.payment.currency.v1.ExchangeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code payment.currency.v1.ExchangeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:payment.currency.v1.ExchangeResponse)
      com.josestg.pb.payment.currency.v1.ExchangeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.payment.currency.v1.ExchangeResponse.class, com.josestg.pb.payment.currency.v1.ExchangeResponse.Builder.class);
    }

    // Construct using com.josestg.pb.payment.currency.v1.ExchangeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRatesFieldBuilder();
        internalGetRespondedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (ratesBuilder_ == null) {
        rates_ = java.util.Collections.emptyList();
      } else {
        rates_ = null;
        ratesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      respondedAt_ = null;
      if (respondedAtBuilder_ != null) {
        respondedAtBuilder_.dispose();
        respondedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeResponse_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.ExchangeResponse getDefaultInstanceForType() {
      return com.josestg.pb.payment.currency.v1.ExchangeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.ExchangeResponse build() {
      com.josestg.pb.payment.currency.v1.ExchangeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.ExchangeResponse buildPartial() {
      com.josestg.pb.payment.currency.v1.ExchangeResponse result = new com.josestg.pb.payment.currency.v1.ExchangeResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.josestg.pb.payment.currency.v1.ExchangeResponse result) {
      if (ratesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rates_ = java.util.Collections.unmodifiableList(rates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rates_ = rates_;
      } else {
        result.rates_ = ratesBuilder_.build();
      }
    }

    private void buildPartial0(com.josestg.pb.payment.currency.v1.ExchangeResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.respondedAt_ = respondedAtBuilder_ == null
            ? respondedAt_
            : respondedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.payment.currency.v1.ExchangeResponse) {
        return mergeFrom((com.josestg.pb.payment.currency.v1.ExchangeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.payment.currency.v1.ExchangeResponse other) {
      if (other == com.josestg.pb.payment.currency.v1.ExchangeResponse.getDefaultInstance()) return this;
      if (ratesBuilder_ == null) {
        if (!other.rates_.isEmpty()) {
          if (rates_.isEmpty()) {
            rates_ = other.rates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRatesIsMutable();
            rates_.addAll(other.rates_);
          }
          onChanged();
        }
      } else {
        if (!other.rates_.isEmpty()) {
          if (ratesBuilder_.isEmpty()) {
            ratesBuilder_.dispose();
            ratesBuilder_ = null;
            rates_ = other.rates_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ratesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRatesFieldBuilder() : null;
          } else {
            ratesBuilder_.addAllMessages(other.rates_);
          }
        }
      }
      if (other.hasRespondedAt()) {
        mergeRespondedAt(other.getRespondedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.josestg.pb.payment.currency.v1.Rate m =
                  input.readMessage(
                      com.josestg.pb.payment.currency.v1.Rate.parser(),
                      extensionRegistry);
              if (ratesBuilder_ == null) {
                ensureRatesIsMutable();
                rates_.add(m);
              } else {
                ratesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRespondedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.josestg.pb.payment.currency.v1.Rate> rates_ =
      java.util.Collections.emptyList();
    private void ensureRatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rates_ = new java.util.ArrayList<com.josestg.pb.payment.currency.v1.Rate>(rates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.josestg.pb.payment.currency.v1.Rate, com.josestg.pb.payment.currency.v1.Rate.Builder, com.josestg.pb.payment.currency.v1.RateOrBuilder> ratesBuilder_;

    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public java.util.List<com.josestg.pb.payment.currency.v1.Rate> getRatesList() {
      if (ratesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rates_);
      } else {
        return ratesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public int getRatesCount() {
      if (ratesBuilder_ == null) {
        return rates_.size();
      } else {
        return ratesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public com.josestg.pb.payment.currency.v1.Rate getRates(int index) {
      if (ratesBuilder_ == null) {
        return rates_.get(index);
      } else {
        return ratesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder setRates(
        int index, com.josestg.pb.payment.currency.v1.Rate value) {
      if (ratesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatesIsMutable();
        rates_.set(index, value);
        onChanged();
      } else {
        ratesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder setRates(
        int index, com.josestg.pb.payment.currency.v1.Rate.Builder builderForValue) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.set(index, builderForValue.build());
        onChanged();
      } else {
        ratesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder addRates(com.josestg.pb.payment.currency.v1.Rate value) {
      if (ratesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatesIsMutable();
        rates_.add(value);
        onChanged();
      } else {
        ratesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder addRates(
        int index, com.josestg.pb.payment.currency.v1.Rate value) {
      if (ratesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatesIsMutable();
        rates_.add(index, value);
        onChanged();
      } else {
        ratesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder addRates(
        com.josestg.pb.payment.currency.v1.Rate.Builder builderForValue) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.add(builderForValue.build());
        onChanged();
      } else {
        ratesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder addRates(
        int index, com.josestg.pb.payment.currency.v1.Rate.Builder builderForValue) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.add(index, builderForValue.build());
        onChanged();
      } else {
        ratesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder addAllRates(
        java.lang.Iterable<? extends com.josestg.pb.payment.currency.v1.Rate> values) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rates_);
        onChanged();
      } else {
        ratesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder clearRates() {
      if (ratesBuilder_ == null) {
        rates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ratesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public Builder removeRates(int index) {
      if (ratesBuilder_ == null) {
        ensureRatesIsMutable();
        rates_.remove(index);
        onChanged();
      } else {
        ratesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public com.josestg.pb.payment.currency.v1.Rate.Builder getRatesBuilder(
        int index) {
      return internalGetRatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public com.josestg.pb.payment.currency.v1.RateOrBuilder getRatesOrBuilder(
        int index) {
      if (ratesBuilder_ == null) {
        return rates_.get(index);  } else {
        return ratesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public java.util.List<? extends com.josestg.pb.payment.currency.v1.RateOrBuilder> 
         getRatesOrBuilderList() {
      if (ratesBuilder_ != null) {
        return ratesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rates_);
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public com.josestg.pb.payment.currency.v1.Rate.Builder addRatesBuilder() {
      return internalGetRatesFieldBuilder().addBuilder(
          com.josestg.pb.payment.currency.v1.Rate.getDefaultInstance());
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public com.josestg.pb.payment.currency.v1.Rate.Builder addRatesBuilder(
        int index) {
      return internalGetRatesFieldBuilder().addBuilder(
          index, com.josestg.pb.payment.currency.v1.Rate.getDefaultInstance());
    }
    /**
     * <code>repeated .payment.currency.v1.Rate rates = 1 [json_name = "rates"];</code>
     */
    public java.util.List<com.josestg.pb.payment.currency.v1.Rate.Builder> 
         getRatesBuilderList() {
      return internalGetRatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.josestg.pb.payment.currency.v1.Rate, com.josestg.pb.payment.currency.v1.Rate.Builder, com.josestg.pb.payment.currency.v1.RateOrBuilder> 
        internalGetRatesFieldBuilder() {
      if (ratesBuilder_ == null) {
        ratesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.josestg.pb.payment.currency.v1.Rate, com.josestg.pb.payment.currency.v1.Rate.Builder, com.josestg.pb.payment.currency.v1.RateOrBuilder>(
                rates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rates_ = null;
      }
      return ratesBuilder_;
    }

    private com.google.protobuf.Timestamp respondedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> respondedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     * @return Whether the respondedAt field is set.
     */
    public boolean hasRespondedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     * @return The respondedAt.
     */
    public com.google.protobuf.Timestamp getRespondedAt() {
      if (respondedAtBuilder_ == null) {
        return respondedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : respondedAt_;
      } else {
        return respondedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     */
    public Builder setRespondedAt(com.google.protobuf.Timestamp value) {
      if (respondedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        respondedAt_ = value;
      } else {
        respondedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     */
    public Builder setRespondedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (respondedAtBuilder_ == null) {
        respondedAt_ = builderForValue.build();
      } else {
        respondedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     */
    public Builder mergeRespondedAt(com.google.protobuf.Timestamp value) {
      if (respondedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          respondedAt_ != null &&
          respondedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRespondedAtBuilder().mergeFrom(value);
        } else {
          respondedAt_ = value;
        }
      } else {
        respondedAtBuilder_.mergeFrom(value);
      }
      if (respondedAt_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     */
    public Builder clearRespondedAt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      respondedAt_ = null;
      if (respondedAtBuilder_ != null) {
        respondedAtBuilder_.dispose();
        respondedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getRespondedAtBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRespondedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRespondedAtOrBuilder() {
      if (respondedAtBuilder_ != null) {
        return respondedAtBuilder_.getMessageOrBuilder();
      } else {
        return respondedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : respondedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp responded_at = 2 [json_name = "responded_at"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetRespondedAtFieldBuilder() {
      if (respondedAtBuilder_ == null) {
        respondedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRespondedAt(),
                getParentForChildren(),
                isClean());
        respondedAt_ = null;
      }
      return respondedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:payment.currency.v1.ExchangeResponse)
  }

  // @@protoc_insertion_point(class_scope:payment.currency.v1.ExchangeResponse)
  private static final com.josestg.pb.payment.currency.v1.ExchangeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.payment.currency.v1.ExchangeResponse();
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExchangeResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExchangeResponse>() {
    @java.lang.Override
    public ExchangeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExchangeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExchangeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.ExchangeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

