// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

/**
 * Protobuf type {@code payment.currency.v1.ExchangeRequest}
 */
@com.google.protobuf.Generated
public final class ExchangeRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:payment.currency.v1.ExchangeRequest)
    ExchangeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ExchangeRequest");
  }
  // Use ExchangeRequest.newBuilder() to construct.
  private ExchangeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExchangeRequest() {
    pairs_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.payment.currency.v1.ExchangeRequest.class, com.josestg.pb.payment.currency.v1.ExchangeRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PAIRS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.josestg.pb.payment.currency.v1.Pair> pairs_;
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public java.util.List<com.josestg.pb.payment.currency.v1.Pair> getPairsList() {
    return pairs_;
  }
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.josestg.pb.payment.currency.v1.PairOrBuilder> 
      getPairsOrBuilderList() {
    return pairs_;
  }
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public int getPairsCount() {
    return pairs_.size();
  }
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.Pair getPairs(int index) {
    return pairs_.get(index);
  }
  /**
   * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.PairOrBuilder getPairsOrBuilder(
      int index) {
    return pairs_.get(index);
  }

  public static final int REQUESTED_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp requestedAt_;
  /**
   * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
   * @return Whether the requestedAt field is set.
   */
  @java.lang.Override
  public boolean hasRequestedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
   * @return The requestedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRequestedAt() {
    return requestedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRequestedAtOrBuilder() {
    return requestedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < pairs_.size(); i++) {
      output.writeMessage(1, pairs_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getRequestedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < pairs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, pairs_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRequestedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.payment.currency.v1.ExchangeRequest)) {
      return super.equals(obj);
    }
    com.josestg.pb.payment.currency.v1.ExchangeRequest other = (com.josestg.pb.payment.currency.v1.ExchangeRequest) obj;

    if (!getPairsList()
        .equals(other.getPairsList())) return false;
    if (hasRequestedAt() != other.hasRequestedAt()) return false;
    if (hasRequestedAt()) {
      if (!getRequestedAt()
          .equals(other.getRequestedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPairsCount() > 0) {
      hash = (37 * hash) + PAIRS_FIELD_NUMBER;
      hash = (53 * hash) + getPairsList().hashCode();
    }
    if (hasRequestedAt()) {
      hash = (37 * hash) + REQUESTED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getRequestedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.ExchangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.payment.currency.v1.ExchangeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code payment.currency.v1.ExchangeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:payment.currency.v1.ExchangeRequest)
      com.josestg.pb.payment.currency.v1.ExchangeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.payment.currency.v1.ExchangeRequest.class, com.josestg.pb.payment.currency.v1.ExchangeRequest.Builder.class);
    }

    // Construct using com.josestg.pb.payment.currency.v1.ExchangeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPairsFieldBuilder();
        internalGetRequestedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (pairsBuilder_ == null) {
        pairs_ = java.util.Collections.emptyList();
      } else {
        pairs_ = null;
        pairsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      requestedAt_ = null;
      if (requestedAtBuilder_ != null) {
        requestedAtBuilder_.dispose();
        requestedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_ExchangeRequest_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.ExchangeRequest getDefaultInstanceForType() {
      return com.josestg.pb.payment.currency.v1.ExchangeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.ExchangeRequest build() {
      com.josestg.pb.payment.currency.v1.ExchangeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.ExchangeRequest buildPartial() {
      com.josestg.pb.payment.currency.v1.ExchangeRequest result = new com.josestg.pb.payment.currency.v1.ExchangeRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.josestg.pb.payment.currency.v1.ExchangeRequest result) {
      if (pairsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pairs_ = java.util.Collections.unmodifiableList(pairs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pairs_ = pairs_;
      } else {
        result.pairs_ = pairsBuilder_.build();
      }
    }

    private void buildPartial0(com.josestg.pb.payment.currency.v1.ExchangeRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestedAt_ = requestedAtBuilder_ == null
            ? requestedAt_
            : requestedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.payment.currency.v1.ExchangeRequest) {
        return mergeFrom((com.josestg.pb.payment.currency.v1.ExchangeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.payment.currency.v1.ExchangeRequest other) {
      if (other == com.josestg.pb.payment.currency.v1.ExchangeRequest.getDefaultInstance()) return this;
      if (pairsBuilder_ == null) {
        if (!other.pairs_.isEmpty()) {
          if (pairs_.isEmpty()) {
            pairs_ = other.pairs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePairsIsMutable();
            pairs_.addAll(other.pairs_);
          }
          onChanged();
        }
      } else {
        if (!other.pairs_.isEmpty()) {
          if (pairsBuilder_.isEmpty()) {
            pairsBuilder_.dispose();
            pairsBuilder_ = null;
            pairs_ = other.pairs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            pairsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPairsFieldBuilder() : null;
          } else {
            pairsBuilder_.addAllMessages(other.pairs_);
          }
        }
      }
      if (other.hasRequestedAt()) {
        mergeRequestedAt(other.getRequestedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.josestg.pb.payment.currency.v1.Pair m =
                  input.readMessage(
                      com.josestg.pb.payment.currency.v1.Pair.parser(),
                      extensionRegistry);
              if (pairsBuilder_ == null) {
                ensurePairsIsMutable();
                pairs_.add(m);
              } else {
                pairsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRequestedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.josestg.pb.payment.currency.v1.Pair> pairs_ =
      java.util.Collections.emptyList();
    private void ensurePairsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pairs_ = new java.util.ArrayList<com.josestg.pb.payment.currency.v1.Pair>(pairs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.josestg.pb.payment.currency.v1.Pair, com.josestg.pb.payment.currency.v1.Pair.Builder, com.josestg.pb.payment.currency.v1.PairOrBuilder> pairsBuilder_;

    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public java.util.List<com.josestg.pb.payment.currency.v1.Pair> getPairsList() {
      if (pairsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pairs_);
      } else {
        return pairsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public int getPairsCount() {
      if (pairsBuilder_ == null) {
        return pairs_.size();
      } else {
        return pairsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public com.josestg.pb.payment.currency.v1.Pair getPairs(int index) {
      if (pairsBuilder_ == null) {
        return pairs_.get(index);
      } else {
        return pairsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder setPairs(
        int index, com.josestg.pb.payment.currency.v1.Pair value) {
      if (pairsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePairsIsMutable();
        pairs_.set(index, value);
        onChanged();
      } else {
        pairsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder setPairs(
        int index, com.josestg.pb.payment.currency.v1.Pair.Builder builderForValue) {
      if (pairsBuilder_ == null) {
        ensurePairsIsMutable();
        pairs_.set(index, builderForValue.build());
        onChanged();
      } else {
        pairsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder addPairs(com.josestg.pb.payment.currency.v1.Pair value) {
      if (pairsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePairsIsMutable();
        pairs_.add(value);
        onChanged();
      } else {
        pairsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder addPairs(
        int index, com.josestg.pb.payment.currency.v1.Pair value) {
      if (pairsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePairsIsMutable();
        pairs_.add(index, value);
        onChanged();
      } else {
        pairsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder addPairs(
        com.josestg.pb.payment.currency.v1.Pair.Builder builderForValue) {
      if (pairsBuilder_ == null) {
        ensurePairsIsMutable();
        pairs_.add(builderForValue.build());
        onChanged();
      } else {
        pairsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder addPairs(
        int index, com.josestg.pb.payment.currency.v1.Pair.Builder builderForValue) {
      if (pairsBuilder_ == null) {
        ensurePairsIsMutable();
        pairs_.add(index, builderForValue.build());
        onChanged();
      } else {
        pairsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder addAllPairs(
        java.lang.Iterable<? extends com.josestg.pb.payment.currency.v1.Pair> values) {
      if (pairsBuilder_ == null) {
        ensurePairsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pairs_);
        onChanged();
      } else {
        pairsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearPairs() {
      if (pairsBuilder_ == null) {
        pairs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pairsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public Builder removePairs(int index) {
      if (pairsBuilder_ == null) {
        ensurePairsIsMutable();
        pairs_.remove(index);
        onChanged();
      } else {
        pairsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public com.josestg.pb.payment.currency.v1.Pair.Builder getPairsBuilder(
        int index) {
      return internalGetPairsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public com.josestg.pb.payment.currency.v1.PairOrBuilder getPairsOrBuilder(
        int index) {
      if (pairsBuilder_ == null) {
        return pairs_.get(index);  } else {
        return pairsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public java.util.List<? extends com.josestg.pb.payment.currency.v1.PairOrBuilder> 
         getPairsOrBuilderList() {
      if (pairsBuilder_ != null) {
        return pairsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pairs_);
      }
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public com.josestg.pb.payment.currency.v1.Pair.Builder addPairsBuilder() {
      return internalGetPairsFieldBuilder().addBuilder(
          com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance());
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public com.josestg.pb.payment.currency.v1.Pair.Builder addPairsBuilder(
        int index) {
      return internalGetPairsFieldBuilder().addBuilder(
          index, com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance());
    }
    /**
     * <code>repeated .payment.currency.v1.Pair pairs = 1 [json_name = "pairs", (.buf.validate.field) = { ... }</code>
     */
    public java.util.List<com.josestg.pb.payment.currency.v1.Pair.Builder> 
         getPairsBuilderList() {
      return internalGetPairsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.josestg.pb.payment.currency.v1.Pair, com.josestg.pb.payment.currency.v1.Pair.Builder, com.josestg.pb.payment.currency.v1.PairOrBuilder> 
        internalGetPairsFieldBuilder() {
      if (pairsBuilder_ == null) {
        pairsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.josestg.pb.payment.currency.v1.Pair, com.josestg.pb.payment.currency.v1.Pair.Builder, com.josestg.pb.payment.currency.v1.PairOrBuilder>(
                pairs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pairs_ = null;
      }
      return pairsBuilder_;
    }

    private com.google.protobuf.Timestamp requestedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> requestedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     * @return Whether the requestedAt field is set.
     */
    public boolean hasRequestedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     * @return The requestedAt.
     */
    public com.google.protobuf.Timestamp getRequestedAt() {
      if (requestedAtBuilder_ == null) {
        return requestedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
      } else {
        return requestedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setRequestedAt(com.google.protobuf.Timestamp value) {
      if (requestedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestedAt_ = value;
      } else {
        requestedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder setRequestedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (requestedAtBuilder_ == null) {
        requestedAt_ = builderForValue.build();
      } else {
        requestedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeRequestedAt(com.google.protobuf.Timestamp value) {
      if (requestedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          requestedAt_ != null &&
          requestedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRequestedAtBuilder().mergeFrom(value);
        } else {
          requestedAt_ = value;
        }
      } else {
        requestedAtBuilder_.mergeFrom(value);
      }
      if (requestedAt_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearRequestedAt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestedAt_ = null;
      if (requestedAtBuilder_ != null) {
        requestedAtBuilder_.dispose();
        requestedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getRequestedAtBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetRequestedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRequestedAtOrBuilder() {
      if (requestedAtBuilder_ != null) {
        return requestedAtBuilder_.getMessageOrBuilder();
      } else {
        return requestedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp requested_at = 2 [json_name = "requested_at", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetRequestedAtFieldBuilder() {
      if (requestedAtBuilder_ == null) {
        requestedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRequestedAt(),
                getParentForChildren(),
                isClean());
        requestedAt_ = null;
      }
      return requestedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:payment.currency.v1.ExchangeRequest)
  }

  // @@protoc_insertion_point(class_scope:payment.currency.v1.ExchangeRequest)
  private static final com.josestg.pb.payment.currency.v1.ExchangeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.payment.currency.v1.ExchangeRequest();
  }

  public static com.josestg.pb.payment.currency.v1.ExchangeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExchangeRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExchangeRequest>() {
    @java.lang.Override
    public ExchangeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExchangeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExchangeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.ExchangeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

