// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

@com.google.protobuf.Generated
public interface PairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payment.currency.v1.Pair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
   * @return The base.
   */
  java.lang.String getBase();
  /**
   * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
   * @return The bytes for base.
   */
  com.google.protobuf.ByteString
      getBaseBytes();

  /**
   * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
   * @return The quote.
   */
  java.lang.String getQuote();
  /**
   * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
   * @return The bytes for quote.
   */
  com.google.protobuf.ByteString
      getQuoteBytes();
}
