// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

/**
 * Protobuf type {@code payment.currency.v1.Pair}
 */
@com.google.protobuf.Generated
public final class Pair extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:payment.currency.v1.Pair)
    PairOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Pair");
  }
  // Use Pair.newBuilder() to construct.
  private Pair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Pair() {
    base_ = "";
    quote_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Pair_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Pair_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.payment.currency.v1.Pair.class, com.josestg.pb.payment.currency.v1.Pair.Builder.class);
  }

  public static final int BASE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object base_ = "";
  /**
   * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
   * @return The base.
   */
  @java.lang.Override
  public java.lang.String getBase() {
    java.lang.Object ref = base_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      base_ = s;
      return s;
    }
  }
  /**
   * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
   * @return The bytes for base.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseBytes() {
    java.lang.Object ref = base_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      base_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quote_ = "";
  /**
   * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
   * @return The quote.
   */
  @java.lang.Override
  public java.lang.String getQuote() {
    java.lang.Object ref = quote_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quote_ = s;
      return s;
    }
  }
  /**
   * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
   * @return The bytes for quote.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuoteBytes() {
    java.lang.Object ref = quote_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quote_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(base_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, base_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quote_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, quote_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(base_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, base_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(quote_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, quote_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.payment.currency.v1.Pair)) {
      return super.equals(obj);
    }
    com.josestg.pb.payment.currency.v1.Pair other = (com.josestg.pb.payment.currency.v1.Pair) obj;

    if (!getBase()
        .equals(other.getBase())) return false;
    if (!getQuote()
        .equals(other.getQuote())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BASE_FIELD_NUMBER;
    hash = (53 * hash) + getBase().hashCode();
    hash = (37 * hash) + QUOTE_FIELD_NUMBER;
    hash = (53 * hash) + getQuote().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.payment.currency.v1.Pair parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.payment.currency.v1.Pair parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.Pair parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.payment.currency.v1.Pair prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code payment.currency.v1.Pair}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:payment.currency.v1.Pair)
      com.josestg.pb.payment.currency.v1.PairOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Pair_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Pair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.payment.currency.v1.Pair.class, com.josestg.pb.payment.currency.v1.Pair.Builder.class);
    }

    // Construct using com.josestg.pb.payment.currency.v1.Pair.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      base_ = "";
      quote_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Pair_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.Pair getDefaultInstanceForType() {
      return com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.Pair build() {
      com.josestg.pb.payment.currency.v1.Pair result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.Pair buildPartial() {
      com.josestg.pb.payment.currency.v1.Pair result = new com.josestg.pb.payment.currency.v1.Pair(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.josestg.pb.payment.currency.v1.Pair result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.base_ = base_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quote_ = quote_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.payment.currency.v1.Pair) {
        return mergeFrom((com.josestg.pb.payment.currency.v1.Pair)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.payment.currency.v1.Pair other) {
      if (other == com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance()) return this;
      if (!other.getBase().isEmpty()) {
        base_ = other.base_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getQuote().isEmpty()) {
        quote_ = other.quote_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              base_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              quote_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object base_ = "";
    /**
     * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
     * @return The base.
     */
    public java.lang.String getBase() {
      java.lang.Object ref = base_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        base_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
     * @return The bytes for base.
     */
    public com.google.protobuf.ByteString
        getBaseBytes() {
      java.lang.Object ref = base_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        base_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
     * @param value The base to set.
     * @return This builder for chaining.
     */
    public Builder setBase(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      base_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearBase() {
      base_ = getDefaultInstance().getBase();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string base = 1 [json_name = "base", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for base to set.
     * @return This builder for chaining.
     */
    public Builder setBaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      base_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object quote_ = "";
    /**
     * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
     * @return The quote.
     */
    public java.lang.String getQuote() {
      java.lang.Object ref = quote_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quote_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
     * @return The bytes for quote.
     */
    public com.google.protobuf.ByteString
        getQuoteBytes() {
      java.lang.Object ref = quote_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quote_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
     * @param value The quote to set.
     * @return This builder for chaining.
     */
    public Builder setQuote(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quote_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearQuote() {
      quote_ = getDefaultInstance().getQuote();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string quote = 2 [json_name = "quote", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for quote to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quote_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:payment.currency.v1.Pair)
  }

  // @@protoc_insertion_point(class_scope:payment.currency.v1.Pair)
  private static final com.josestg.pb.payment.currency.v1.Pair DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.payment.currency.v1.Pair();
  }

  public static com.josestg.pb.payment.currency.v1.Pair getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Pair>
      PARSER = new com.google.protobuf.AbstractParser<Pair>() {
    @java.lang.Override
    public Pair parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Pair> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Pair> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.Pair getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

