// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

/**
 * Protobuf type {@code payment.currency.v1.Rate}
 */
@com.google.protobuf.Generated
public final class Rate extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:payment.currency.v1.Rate)
    RateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Rate");
  }
  // Use Rate.newBuilder() to construct.
  private Rate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Rate() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Rate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Rate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.josestg.pb.payment.currency.v1.Rate.class, com.josestg.pb.payment.currency.v1.Rate.Builder.class);
  }

  private int bitField0_;
  public static final int PAIR_FIELD_NUMBER = 1;
  private com.josestg.pb.payment.currency.v1.Pair pair_;
  /**
   * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
   * @return Whether the pair field is set.
   */
  @java.lang.Override
  public boolean hasPair() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
   * @return The pair.
   */
  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.Pair getPair() {
    return pair_ == null ? com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance() : pair_;
  }
  /**
   * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
   */
  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.PairOrBuilder getPairOrBuilder() {
    return pair_ == null ? com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance() : pair_;
  }

  public static final int RATE_FIELD_NUMBER = 2;
  private double rate_ = 0D;
  /**
   * <code>double rate = 2 [json_name = "rate"];</code>
   * @return The rate.
   */
  @java.lang.Override
  public double getRate() {
    return rate_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPair());
    }
    if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
      output.writeDouble(2, rate_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getTimestamp());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPair());
    }
    if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, rate_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTimestamp());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.josestg.pb.payment.currency.v1.Rate)) {
      return super.equals(obj);
    }
    com.josestg.pb.payment.currency.v1.Rate other = (com.josestg.pb.payment.currency.v1.Rate) obj;

    if (hasPair() != other.hasPair()) return false;
    if (hasPair()) {
      if (!getPair()
          .equals(other.getPair())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getRate())
        != java.lang.Double.doubleToLongBits(
            other.getRate())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPair()) {
      hash = (37 * hash) + PAIR_FIELD_NUMBER;
      hash = (53 * hash) + getPair().hashCode();
    }
    hash = (37 * hash) + RATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRate()));
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.josestg.pb.payment.currency.v1.Rate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.josestg.pb.payment.currency.v1.Rate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.josestg.pb.payment.currency.v1.Rate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.josestg.pb.payment.currency.v1.Rate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code payment.currency.v1.Rate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:payment.currency.v1.Rate)
      com.josestg.pb.payment.currency.v1.RateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Rate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Rate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.josestg.pb.payment.currency.v1.Rate.class, com.josestg.pb.payment.currency.v1.Rate.Builder.class);
    }

    // Construct using com.josestg.pb.payment.currency.v1.Rate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPairFieldBuilder();
        internalGetTimestampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pair_ = null;
      if (pairBuilder_ != null) {
        pairBuilder_.dispose();
        pairBuilder_ = null;
      }
      rate_ = 0D;
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.josestg.pb.payment.currency.v1.Currency.internal_static_payment_currency_v1_Rate_descriptor;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.Rate getDefaultInstanceForType() {
      return com.josestg.pb.payment.currency.v1.Rate.getDefaultInstance();
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.Rate build() {
      com.josestg.pb.payment.currency.v1.Rate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.josestg.pb.payment.currency.v1.Rate buildPartial() {
      com.josestg.pb.payment.currency.v1.Rate result = new com.josestg.pb.payment.currency.v1.Rate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.josestg.pb.payment.currency.v1.Rate result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pair_ = pairBuilder_ == null
            ? pair_
            : pairBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rate_ = rate_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.josestg.pb.payment.currency.v1.Rate) {
        return mergeFrom((com.josestg.pb.payment.currency.v1.Rate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.josestg.pb.payment.currency.v1.Rate other) {
      if (other == com.josestg.pb.payment.currency.v1.Rate.getDefaultInstance()) return this;
      if (other.hasPair()) {
        mergePair(other.getPair());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getRate()) != 0) {
        setRate(other.getRate());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetPairFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              rate_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              input.readMessage(
                  internalGetTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.josestg.pb.payment.currency.v1.Pair pair_;
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.payment.currency.v1.Pair, com.josestg.pb.payment.currency.v1.Pair.Builder, com.josestg.pb.payment.currency.v1.PairOrBuilder> pairBuilder_;
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     * @return Whether the pair field is set.
     */
    public boolean hasPair() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     * @return The pair.
     */
    public com.josestg.pb.payment.currency.v1.Pair getPair() {
      if (pairBuilder_ == null) {
        return pair_ == null ? com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance() : pair_;
      } else {
        return pairBuilder_.getMessage();
      }
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     */
    public Builder setPair(com.josestg.pb.payment.currency.v1.Pair value) {
      if (pairBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pair_ = value;
      } else {
        pairBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     */
    public Builder setPair(
        com.josestg.pb.payment.currency.v1.Pair.Builder builderForValue) {
      if (pairBuilder_ == null) {
        pair_ = builderForValue.build();
      } else {
        pairBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     */
    public Builder mergePair(com.josestg.pb.payment.currency.v1.Pair value) {
      if (pairBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          pair_ != null &&
          pair_ != com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance()) {
          getPairBuilder().mergeFrom(value);
        } else {
          pair_ = value;
        }
      } else {
        pairBuilder_.mergeFrom(value);
      }
      if (pair_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     */
    public Builder clearPair() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pair_ = null;
      if (pairBuilder_ != null) {
        pairBuilder_.dispose();
        pairBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     */
    public com.josestg.pb.payment.currency.v1.Pair.Builder getPairBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetPairFieldBuilder().getBuilder();
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     */
    public com.josestg.pb.payment.currency.v1.PairOrBuilder getPairOrBuilder() {
      if (pairBuilder_ != null) {
        return pairBuilder_.getMessageOrBuilder();
      } else {
        return pair_ == null ?
            com.josestg.pb.payment.currency.v1.Pair.getDefaultInstance() : pair_;
      }
    }
    /**
     * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.josestg.pb.payment.currency.v1.Pair, com.josestg.pb.payment.currency.v1.Pair.Builder, com.josestg.pb.payment.currency.v1.PairOrBuilder> 
        internalGetPairFieldBuilder() {
      if (pairBuilder_ == null) {
        pairBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.josestg.pb.payment.currency.v1.Pair, com.josestg.pb.payment.currency.v1.Pair.Builder, com.josestg.pb.payment.currency.v1.PairOrBuilder>(
                getPair(),
                getParentForChildren(),
                isClean());
        pair_ = null;
      }
      return pairBuilder_;
    }

    private double rate_ ;
    /**
     * <code>double rate = 2 [json_name = "rate"];</code>
     * @return The rate.
     */
    @java.lang.Override
    public double getRate() {
      return rate_;
    }
    /**
     * <code>double rate = 2 [json_name = "rate"];</code>
     * @param value The rate to set.
     * @return This builder for chaining.
     */
    public Builder setRate(double value) {

      rate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double rate = 2 [json_name = "rate"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rate_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          timestamp_ != null &&
          timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:payment.currency.v1.Rate)
  }

  // @@protoc_insertion_point(class_scope:payment.currency.v1.Rate)
  private static final com.josestg.pb.payment.currency.v1.Rate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.josestg.pb.payment.currency.v1.Rate();
  }

  public static com.josestg.pb.payment.currency.v1.Rate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rate>
      PARSER = new com.google.protobuf.AbstractParser<Rate>() {
    @java.lang.Override
    public Rate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Rate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Rate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.josestg.pb.payment.currency.v1.Rate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

