// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/currency/v1/currency.proto
// Protobuf Java Version: 4.33.1

package com.josestg.pb.payment.currency.v1;

@com.google.protobuf.Generated
public interface RateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payment.currency.v1.Rate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
   * @return Whether the pair field is set.
   */
  boolean hasPair();
  /**
   * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
   * @return The pair.
   */
  com.josestg.pb.payment.currency.v1.Pair getPair();
  /**
   * <code>.payment.currency.v1.Pair pair = 1 [json_name = "pair"];</code>
   */
  com.josestg.pb.payment.currency.v1.PairOrBuilder getPairOrBuilder();

  /**
   * <code>double rate = 2 [json_name = "rate"];</code>
   * @return The rate.
   */
  double getRate();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
