// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: team/project/feature/v1/example.proto

package featurepb

import (
	v1 "github.com/josestg/pb/go/identity/session/v1"
	v11 "github.com/josestg/pb/go/shared/audit/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Create        *v1.CreateRequest      `protobuf:"bytes,1,opt,name=create,proto3" json:"create,omitempty"`
	Audit         *v11.Audit             `protobuf:"bytes,2,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleRequest) Reset() {
	*x = ExampleRequest{}
	mi := &file_team_project_feature_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRequest) ProtoMessage() {}

func (x *ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_project_feature_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRequest.ProtoReflect.Descriptor instead.
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return file_team_project_feature_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleRequest) GetCreate() *v1.CreateRequest {
	if x != nil {
		return x.Create
	}
	return nil
}

func (x *ExampleRequest) GetAudit() *v11.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SomeTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=some_time,proto3" json:"some_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_team_project_feature_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_project_feature_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_team_project_feature_v1_example_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleResponse) GetSomeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SomeTime
	}
	return nil
}

var File_team_project_feature_v1_example_proto protoreflect.FileDescriptor

const file_team_project_feature_v1_example_proto_rawDesc = "" +
	"\n" +
	"%team/project/feature/v1/example.proto\x12\x17team.project.feature.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!identity/session/v1/session.proto\x1a\x1bshared/audit/v1/audit.proto\"z\n" +
	"\x0eExampleRequest\x12:\n" +
	"\x06create\x18\x01 \x01(\v2\".identity.session.v1.CreateRequestR\x06create\x12,\n" +
	"\x05audit\x18\x02 \x01(\v2\x16.shared.audit.v1.AuditR\x05audit\"K\n" +
	"\x0fExampleResponse\x128\n" +
	"\tsome_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tsome_time2\x98\x01\n" +
	"\x0eExampleService\x12\x85\x01\n" +
	"\aExample\x12'.team.project.feature.v1.ExampleRequest\x1a(.team.project.feature.v1.ExampleResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/team-project/api/v1/featureBf\n" +
	"&com.josestg.pb.team.project.feature.v1P\x01Z:github.com/josestg/pb/go/team/project/feature/v1;featurepbb\x06proto3"

var (
	file_team_project_feature_v1_example_proto_rawDescOnce sync.Once
	file_team_project_feature_v1_example_proto_rawDescData []byte
)

func file_team_project_feature_v1_example_proto_rawDescGZIP() []byte {
	file_team_project_feature_v1_example_proto_rawDescOnce.Do(func() {
		file_team_project_feature_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_project_feature_v1_example_proto_rawDesc), len(file_team_project_feature_v1_example_proto_rawDesc)))
	})
	return file_team_project_feature_v1_example_proto_rawDescData
}

var file_team_project_feature_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_team_project_feature_v1_example_proto_goTypes = []any{
	(*ExampleRequest)(nil),        // 0: team.project.feature.v1.ExampleRequest
	(*ExampleResponse)(nil),       // 1: team.project.feature.v1.ExampleResponse
	(*v1.CreateRequest)(nil),      // 2: identity.session.v1.CreateRequest
	(*v11.Audit)(nil),             // 3: shared.audit.v1.Audit
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_team_project_feature_v1_example_proto_depIdxs = []int32{
	2, // 0: team.project.feature.v1.ExampleRequest.create:type_name -> identity.session.v1.CreateRequest
	3, // 1: team.project.feature.v1.ExampleRequest.audit:type_name -> shared.audit.v1.Audit
	4, // 2: team.project.feature.v1.ExampleResponse.some_time:type_name -> google.protobuf.Timestamp
	0, // 3: team.project.feature.v1.ExampleService.Example:input_type -> team.project.feature.v1.ExampleRequest
	1, // 4: team.project.feature.v1.ExampleService.Example:output_type -> team.project.feature.v1.ExampleResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_team_project_feature_v1_example_proto_init() }
func file_team_project_feature_v1_example_proto_init() {
	if File_team_project_feature_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_project_feature_v1_example_proto_rawDesc), len(file_team_project_feature_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_project_feature_v1_example_proto_goTypes,
		DependencyIndexes: file_team_project_feature_v1_example_proto_depIdxs,
		MessageInfos:      file_team_project_feature_v1_example_proto_msgTypes,
	}.Build()
	File_team_project_feature_v1_example_proto = out.File
	file_team_project_feature_v1_example_proto_goTypes = nil
	file_team_project_feature_v1_example_proto_depIdxs = nil
}
