// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: identity/session/v1/session.proto

package sessionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreateService_Create_FullMethodName = "/identity.session.v1.CreateService/Create"
)

// CreateServiceClient is the client API for CreateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type createServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateServiceClient(cc grpc.ClientConnInterface) CreateServiceClient {
	return &createServiceClient{cc}
}

func (c *createServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, CreateService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateServiceServer is the server API for CreateService service.
// All implementations should embed UnimplementedCreateServiceServer
// for forward compatibility.
type CreateServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

// UnimplementedCreateServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreateServiceServer struct{}

func (UnimplementedCreateServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCreateServiceServer) testEmbeddedByValue() {}

// UnsafeCreateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateServiceServer will
// result in compilation errors.
type UnsafeCreateServiceServer interface {
	mustEmbedUnimplementedCreateServiceServer()
}

func RegisterCreateServiceServer(s grpc.ServiceRegistrar, srv CreateServiceServer) {
	// If the following call pancis, it indicates UnimplementedCreateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreateService_ServiceDesc, srv)
}

func _CreateService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateService_ServiceDesc is the grpc.ServiceDesc for CreateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.session.v1.CreateService",
	HandlerType: (*CreateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CreateService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/session/v1/session.proto",
}

const (
	RevokeService_Revoke_FullMethodName = "/identity.session.v1.RevokeService/Revoke"
)

// RevokeServiceClient is the client API for RevokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevokeServiceClient interface {
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
}

type revokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRevokeServiceClient(cc grpc.ClientConnInterface) RevokeServiceClient {
	return &revokeServiceClient{cc}
}

func (c *revokeServiceClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, RevokeService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevokeServiceServer is the server API for RevokeService service.
// All implementations should embed UnimplementedRevokeServiceServer
// for forward compatibility.
type RevokeServiceServer interface {
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
}

// UnimplementedRevokeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevokeServiceServer struct{}

func (UnimplementedRevokeServiceServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedRevokeServiceServer) testEmbeddedByValue() {}

// UnsafeRevokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevokeServiceServer will
// result in compilation errors.
type UnsafeRevokeServiceServer interface {
	mustEmbedUnimplementedRevokeServiceServer()
}

func RegisterRevokeServiceServer(s grpc.ServiceRegistrar, srv RevokeServiceServer) {
	// If the following call pancis, it indicates UnimplementedRevokeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RevokeService_ServiceDesc, srv)
}

func _RevokeService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevokeServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevokeService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevokeServiceServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RevokeService_ServiceDesc is the grpc.ServiceDesc for RevokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.session.v1.RevokeService",
	HandlerType: (*RevokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Revoke",
			Handler:    _RevokeService_Revoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/session/v1/session.proto",
}
