// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: identity/session/v1/session.proto

package sessionpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/josestg/pb/go/identity/token/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_identity_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_identity_session_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	RefreshToken  *v1.Token              `protobuf:"bytes,2,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_identity_session_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_session_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_identity_session_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *CreateResponse) GetRefreshToken() *v1.Token {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	RefreshToken  *v1.Token              `protobuf:"bytes,2,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_identity_session_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_session_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_identity_session_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *RevokeRequest) GetRefreshToken() *v1.Token {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jti           string                 `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revoked_at,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_identity_session_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_session_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_identity_session_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeResponse) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *RevokeResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

var File_identity_session_v1_session_proto protoreflect.FileDescriptor

const file_identity_session_v1_session_proto_rawDesc = "" +
	"\n" +
	"!identity/session/v1/session.proto\x12\x13identity.session.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1didentity/token/v1/token.proto\x1a\x1bbuf/validate/validate.proto\"}\n" +
	"\rCreateRequest\x12 \n" +
	"\x04name\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x02\x18xR\x04name\x12 \n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12(\n" +
	"\bpassword\x18\x03 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\b\x18@R\bpassword\"\x8e\x01\n" +
	"\x0eCreateResponse\x12<\n" +
	"\faccess_token\x18\x01 \x01(\v2\x18.identity.token.v1.TokenR\faccess_token\x12>\n" +
	"\rrefresh_token\x18\x02 \x01(\v2\x18.identity.token.v1.TokenR\rrefresh_token\"\x8d\x01\n" +
	"\rRevokeRequest\x12<\n" +
	"\faccess_token\x18\x01 \x01(\v2\x18.identity.token.v1.TokenR\faccess_token\x12>\n" +
	"\rrefresh_token\x18\x02 \x01(\v2\x18.identity.token.v1.TokenR\rrefresh_token\"x\n" +
	"\x0eRevokeResponse\x12\x1d\n" +
	"\x03jti\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x88\x02\x01R\x03jti\x12G\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\v\xbaH\b\xc8\x01\x01\xb2\x01\x02@\x01R\n" +
	"revoked_at2d\n" +
	"\rCreateService\x12S\n" +
	"\x06Create\x12\".identity.session.v1.CreateRequest\x1a#.identity.session.v1.CreateResponse\"\x002d\n" +
	"\rRevokeService\x12S\n" +
	"\x06Revoke\x12\".identity.session.v1.RevokeRequest\x1a#.identity.session.v1.RevokeResponse\"\x00BU\n" +
	"\x19com.josestg.pb.session.v1P\x01Z6github.com/josestg/pb/go/identity/session/v1;sessionpbb\x06proto3"

var (
	file_identity_session_v1_session_proto_rawDescOnce sync.Once
	file_identity_session_v1_session_proto_rawDescData []byte
)

func file_identity_session_v1_session_proto_rawDescGZIP() []byte {
	file_identity_session_v1_session_proto_rawDescOnce.Do(func() {
		file_identity_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_session_v1_session_proto_rawDesc), len(file_identity_session_v1_session_proto_rawDesc)))
	})
	return file_identity_session_v1_session_proto_rawDescData
}

var file_identity_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_identity_session_v1_session_proto_goTypes = []any{
	(*CreateRequest)(nil),         // 0: identity.session.v1.CreateRequest
	(*CreateResponse)(nil),        // 1: identity.session.v1.CreateResponse
	(*RevokeRequest)(nil),         // 2: identity.session.v1.RevokeRequest
	(*RevokeResponse)(nil),        // 3: identity.session.v1.RevokeResponse
	(*v1.Token)(nil),              // 4: identity.token.v1.Token
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_identity_session_v1_session_proto_depIdxs = []int32{
	4, // 0: identity.session.v1.CreateResponse.access_token:type_name -> identity.token.v1.Token
	4, // 1: identity.session.v1.CreateResponse.refresh_token:type_name -> identity.token.v1.Token
	4, // 2: identity.session.v1.RevokeRequest.access_token:type_name -> identity.token.v1.Token
	4, // 3: identity.session.v1.RevokeRequest.refresh_token:type_name -> identity.token.v1.Token
	5, // 4: identity.session.v1.RevokeResponse.revoked_at:type_name -> google.protobuf.Timestamp
	0, // 5: identity.session.v1.CreateService.Create:input_type -> identity.session.v1.CreateRequest
	2, // 6: identity.session.v1.RevokeService.Revoke:input_type -> identity.session.v1.RevokeRequest
	1, // 7: identity.session.v1.CreateService.Create:output_type -> identity.session.v1.CreateResponse
	3, // 8: identity.session.v1.RevokeService.Revoke:output_type -> identity.session.v1.RevokeResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_identity_session_v1_session_proto_init() }
func file_identity_session_v1_session_proto_init() {
	if File_identity_session_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_session_v1_session_proto_rawDesc), len(file_identity_session_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_identity_session_v1_session_proto_goTypes,
		DependencyIndexes: file_identity_session_v1_session_proto_depIdxs,
		MessageInfos:      file_identity_session_v1_session_proto_msgTypes,
	}.Build()
	File_identity_session_v1_session_proto = out.File
	file_identity_session_v1_session_proto_goTypes = nil
	file_identity_session_v1_session_proto_depIdxs = nil
}
